import { createClient } from 'npm:@supabase/supabase-js@2.39.3';

interface FabricInfo {
  id: string;
  label: string;
}

async function fetchFabricLabel(
  supabase: ReturnType<typeof createClient>,
  fabricType: string | undefined,
): Promise<string> {
  if (!fabricType) return 'Custom';
  const { data, error } = await supabase
    .from('fabric_catalog')
    .select('label')
    .eq('id', fabricType)
    .maybeSingle();
  if (error || !data?.label) {
    console.warn(`[save-quote] Could not resolve fabric label for id "${fabricType}"`);
    return 'Custom';
  }
  return data.label as string;
}

async function generateDefaultQuoteName(
  supabase: ReturnType<typeof createClient>,
  config: any,
): Promise<string> {
  const corners = config?.corners || 3;
  const fabricType = config?.fabricType;
  const fabricColor = config?.fabricColor;

  const fabricLabel = await fetchFabricLabel(supabase, fabricType);

  const now = new Date();
  const month = now.toLocaleDateString('en-US', { month: 'short' });
  const day = now.getDate();

  let quoteName = `${corners}-Corner ${fabricLabel}`;

  if (fabricColor) {
    quoteName += ` ${fabricColor}`;
  }

  quoteName += ` Shade Sail - ${month} ${day}`;

  if (quoteName.length > 100) {
    quoteName = quoteName.substring(0, 97) + '...';
  }

  return quoteName;
}

async function lookupGeo(ip: string): Promise<{ country: string; countryCode: string } | null> {
  if (!ip || ip === 'unknown') return null;
  const cleanIp = ip.split(',')[0].trim();
  if (!cleanIp || cleanIp === '127.0.0.1' || cleanIp === '::1') return null;

  try {
    const res = await fetch(`http://ip-api.com/json/${cleanIp}?fields=status,country,countryCode`);
    if (!res.ok) return null;
    const data = await res.json();
    if (data.status === 'success') {
      return { country: data.country, countryCode: data.countryCode };
    }
  } catch {
    // geo lookup failure should never block quote saving
  }
  return null;
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    if (req.method === 'POST') {
      // Save a new quote
      const { config, calculations, email, quoteName, customerReference, currentStep, totalSteps, pricingSnapshot, firstName, lastName, canvasImageUrl } = await req.json();

      if (!config || !calculations) {
        return new Response(
          JSON.stringify({ error: 'Missing required fields: config and calculations' }),
          { 
            status: 400, 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
          }
        );
      }

      // Generate unique quote reference
      const { data: refData, error: refError } = await supabase
        .rpc('generate_quote_reference');

      if (refError) {
        throw new Error(`Failed to generate quote reference: ${refError.message}`);
      }

      const quoteReference = refData;

      let finalQuoteName = quoteName?.trim() || '';
      let nameAutoGenerated = false;

      if (!finalQuoteName) {
        finalQuoteName = await generateDefaultQuoteName(supabase, config);
        nameAutoGenerated = true;
      }

      if (finalQuoteName.length > 100) {
        finalQuoteName = finalQuoteName.substring(0, 100);
      }

      let finalCustomerReference = customerReference?.trim() || null;
      if (finalCustomerReference && finalCustomerReference.length > 50) {
        finalCustomerReference = finalCustomerReference.substring(0, 50);
      }

      // Generate access token
      const { data: tokenData, error: tokenError } = await supabase
        .rpc('generate_access_token');

      if (tokenError) {
        throw new Error(`Failed to generate access token: ${tokenError.message}`);
      }

      const accessToken = tokenData;

      // Generate user identifier if email provided
      let userIdentifier = null;
      if (email) {
        const { data: identifierData, error: identifierError } = await supabase
          .rpc('get_user_identifier', { email });

        if (!identifierError) {
          userIdentifier = identifierData;
        }
      }

      // Determine status based on completion
      // If currentStep is 6 (final review step) and all required steps are complete, it's a complete quote
      // Otherwise, it's in progress
      const isComplete = currentStep === 6 || currentStep === totalSteps - 1;
      const quoteStatus = isComplete ? 'quote_ready' : 'in_progress';

      const rawIpHeader = req.headers.get('x-forwarded-for') || req.headers.get('x-real-ip') || 'unknown';
      const customerIp = rawIpHeader === 'unknown' ? 'unknown' : (rawIpHeader.split(',')[0].trim() || 'unknown');
      const geo = await lookupGeo(customerIp);

      // Capture an authoritative locked total at save time. Restored verbatim on resume
      // while pricing is locked, and forwarded to Shopify so cart layers anchor on it.
      const quoteCurrency: string | null = config?.currency || null;
      const lockedTotal: number | null =
        typeof calculations?.totalPrice === 'number' ? calculations.totalPrice : null;
      const sailOnlyNzd = Number(calculations?.hardwareBreakdown?.sailOnlyPriceNzd ?? 0);
      const hardwareOnlyNzd = Number(calculations?.hardwareBreakdown?.hardwareOnlyPriceNzd ?? 0);
      const lockedBaseNzd: number | null =
        Number.isFinite(sailOnlyNzd + hardwareOnlyNzd) ? sailOnlyNzd + hardwareOnlyNzd : null;
      const snapshotEntry =
        pricingSnapshot && quoteCurrency
          ? (pricingSnapshot as Record<string, any>)[quoteCurrency]
          : null;
      const lockedFxRate = snapshotEntry?.exchange_rate ?? null;
      const lockedMarketMarkup = snapshotEntry?.market_markup ?? null;
      const lockedZonosDhlMarkup = snapshotEntry?.zonos_dhl_markup ?? null;

      const { data: quote, error: insertError } = await supabase
        .from('saved_quotes')
        .insert({
          quote_reference: quoteReference,
          quote_name: finalQuoteName,
          customer_reference: finalCustomerReference,
          name_auto_generated: nameAutoGenerated,
          customer_email: email || null,
          access_token: accessToken,
          user_identifier: userIdentifier,
          config_data: config,
          calculations_data: calculations,
          current_step: currentStep ?? null,
          total_steps: totalSteps ?? 7,
          status: quoteStatus,
          pricing_snapshot: pricingSnapshot ?? null,
          locked_total: lockedTotal,
          locked_total_currency: quoteCurrency,
          locked_total_base_nzd: lockedBaseNzd,
          locked_fx_rate: lockedFxRate,
          locked_market_markup: lockedMarketMarkup,
          locked_zonos_dhl_markup: lockedZonosDhlMarkup,
          locked_at: new Date().toISOString(),
          customer_first_name: firstName || null,
          customer_last_name: lastName || null,
          customer_ip: customerIp,
          customer_ip_raw: rawIpHeader,
          customer_country: geo?.country || null,
          customer_country_code: geo?.countryCode || null,
          diagram_public_url: typeof canvasImageUrl === "string" && canvasImageUrl.startsWith("http") ? canvasImageUrl : null,
        })
        .select()
        .single();

      if (insertError) {
        throw new Error(`Failed to save quote: ${insertError.message}`);
      }

      // If email provided, add to Shopify customers
      let shopifyCustomerId: string | null = null;
      let shopifyCustomerCreated = false;

      if (email) {
        try {
          const shopifyResponse = await fetch(
            `${supabaseUrl}/functions/v1/add-shopify-customer`,
            {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${serviceRoleKey}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                email: email,
                firstName: firstName || undefined,
                lastName: lastName || undefined,
                tags: ['quote_saved', 'configurator_user'],
                quoteReference: quoteReference,
                totalPrice: calculations.totalPrice,
                currency: config.currency,
              }),
            }
          );

          const shopifyData = await shopifyResponse.json();

          if (shopifyData.success) {
            shopifyCustomerId = shopifyData.customer.id;
            shopifyCustomerCreated = shopifyData.customer.isNew;

            // Update the quote with Shopify customer ID
            await supabase
              .from('saved_quotes')
              .update({
                shopify_customer_id: shopifyCustomerId,
                source: 'manual_save'
              })
              .eq('id', quote.id);
          }
        } catch (shopifyError) {
          console.error('Failed to add customer to Shopify:', shopifyError);
          // Continue even if Shopify integration fails
        }
      }

      return new Response(
        JSON.stringify({
          success: true,
          quote: {
            id: quote.id,
            reference: quote.quote_reference,
            quoteName: quote.quote_name,
            customerReference: quote.customer_reference,
            nameAutoGenerated: quote.name_auto_generated,
            expiresAt: quote.expires_at,
            pricingLockedUntil: quote.pricing_locked_until,
            accessToken: quote.access_token,
            shopifyCustomerCreated: shopifyCustomerCreated,
            shopifyCustomerId: shopifyCustomerId,
            currentStep: quote.current_step,
            totalSteps: quote.total_steps,
            status: quote.status,
          },
        }),
        {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    if (req.method === 'GET') {
      // Retrieve a quote by ID and access token
      const url = new URL(req.url);
      const id = url.searchParams.get('id');
      const token = url.searchParams.get('token');

      if (!id || !token) {
        return new Response(
          JSON.stringify({ error: 'Missing required parameters: id and token' }),
          {
            status: 400,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          }
        );
      }

      const { data: quote, error } = await supabase
        .from('saved_quotes')
        .select('*')
        .eq('id', id)
        .eq('access_token', token)
        .in('status', ['saved', 'in_progress', 'quote_ready'])
        .maybeSingle();

      if (error) {
        throw new Error(`Failed to retrieve quote: ${error.message}`);
      }

      if (!quote) {
        return new Response(
          JSON.stringify({ error: 'Quote not found or invalid access token' }),
          {
            status: 404,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          }
        );
      }

      await supabase
        .from('saved_quotes')
        .update({ last_accessed_at: new Date().toISOString() })
        .eq('id', quote.id);

      const now = new Date();
      const pricingLockedUntil = quote.pricing_locked_until ? new Date(quote.pricing_locked_until) : null;
      const pricingStatus = pricingLockedUntil && now < pricingLockedUntil ? 'locked' : 'live';

      return new Response(
        JSON.stringify({
          success: true,
          quote: {
            ...quote,
            pricing_status: pricingStatus,
          },
        }),
        {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    if (req.method === 'PATCH') {
      // Update quote status
      const { id, token, status } = await req.json();

      if (!id || !token || !status) {
        return new Response(
          JSON.stringify({ error: 'Missing required fields: id, token, and status' }),
          {
            status: 400,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          }
        );
      }

      const { error } = await supabase
        .from('saved_quotes')
        .update({ status })
        .eq('id', id)
        .eq('access_token', token);

      if (error) {
        throw new Error(`Failed to update quote: ${error.message}`);
      }

      return new Response(
        JSON.stringify({ success: true }),
        { 
          status: 200, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      );
    }

    return new Response(
      JSON.stringify({ error: 'Method not allowed' }),
      { 
        status: 405, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  } catch (error) {
    console.error('Error in save-quote function:', error);
    return new Response(
      JSON.stringify({ error: error.message || 'An unexpected error occurred' }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});