# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cba1909c59e493948c6c4c9141c8350b"
name = "Heidi-Suckling-Hasan"
handle = "heidi-suckling-hasan"
application_url = "https://scroll-picks-indicators-suits.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_publications,"

[auth]
redirect_urls = ["https://scroll-picks-indicators-suits.trycloudflare.com/auth/callback", "https://scroll-picks-indicators-suits.trycloudflare.com/auth/shopify/callback", "https://scroll-picks-indicators-suits.trycloudflare.com/api/auth/callback"]


[app_proxy]
url = "https://scroll-picks-indicators-suits.trycloudflare.com"
subpath = "shade_space"
prefix = "apps"

[pos]
embedded = false
