import React, { useEffect, useMemo, useState } from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { supabase } from '../../lib/supabase';
import {
  BLOCK_LABELS,
  BlockType,
  DEFAULT_BLOCKS,
  DYNAMIC_TYPES,
  PdfBlock,
  getBlockColumn,
  escapeHtml,
  makeDefaultProps,
  newBlockId,
  sanitizeCustomHtml,
} from '../../utils/pdfBlocks';
import { ConfiguratorState, ShadeCalculations } from '../../types';
import { getDiagonalKeysForCorners } from '../../utils/geometry';
import { generatePdfFromBlocks, PdfDensity } from '../../utils/pdfGenerator';

interface LiveQuoteRow {
  id: string;
  quote_reference: string | null;
  quote_name: string | null;
  customer_first_name: string | null;
  customer_last_name: string | null;
  customer_email: string | null;
  customer_reference: string | null;
  access_token: string;
  diagram_public_url: string | null;
  created_at: string;
  config_data: ConfiguratorState;
  calculations_data: ShadeCalculations;
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  NZD: 'NZ$', USD: 'US$', AUD: 'AU$', GBP: '\u00a3', EUR: '\u20ac', CAD: 'CA$',
};

function formatCurrencyPreview(amount: number, code: string): string {
  const symbol = CURRENCY_SYMBOLS[code] || code;
  return `${symbol}${(amount || 0).toFixed(2)}`;
}

function formatMeasurementPreview(mm: number, unit: 'metric' | 'imperial'): string {
  if (!mm || !isFinite(mm)) return 'Not provided';
  if (unit === 'imperial') {
    const inches = mm * 0.0393701;
    if (inches >= 12) {
      const feet = Math.floor(inches / 12);
      const rem = inches % 12;
      return parseFloat(rem.toFixed(1)) > 0 ? `${feet}'${rem.toFixed(1)}"` : `${feet}'`;
    }
    return `${inches.toFixed(1)}"`;
  }
  return `${Math.round(mm)}mm`;
}

function formatAreaPreview(mm2: number, unit: 'metric' | 'imperial'): string {
  if (unit === 'imperial') {
    const sqft = mm2 * (0.0393701 * 0.0393701) / 144;
    return `${sqft.toFixed(1)} ft\u00b2`;
  }
  return `${(mm2 / 1000000).toFixed(2)} m\u00b2`;
}

export interface PdfTemplateConfig {
  brand: {
    primaryColor: string;
    accentColor: string;
    accentDark: string;
    textColor: string;
    mutedColor: string;
    backgroundColor: string;
    logoUrl: string;
    fontFamily: string;
  };
  header: { title: string; tagline: string };
  footer: { line1: string; line2: string };
  sections: {
    showSummary: boolean;
    showMeasurements: boolean;
    showAnchorPoints: boolean;
    showHardwareBreakdown: boolean;
    showPriceBreakdown: boolean;
    showGuarantee: boolean;
    showPricingCallout: boolean;
  };
  paper: 'A4' | 'Letter';
  layout?: {
    density: 'comfortable' | 'compact' | 'ultra';
    columns: 1 | 2;
  };
}

interface PdfTemplateRow {
  id: string;
  name: string;
  is_active: boolean;
  config: PdfTemplateConfig;
  blocks: PdfBlock[];
  updated_at: string;
}

const DEFAULT_CONFIG: PdfTemplateConfig = {
  brand: {
    primaryColor: '#01312D',
    accentColor: '#BFF102',
    accentDark: '#307C31',
    textColor: '#01312D',
    mutedColor: '#64748B',
    backgroundColor: '#FFFFFF',
    logoUrl: '',
    fontFamily: 'Helvetica, Arial, sans-serif',
  },
  header: { title: 'Custom Shade Sail Quote', tagline: 'Where Cool Spaces Begin' },
  footer: {
    line1: 'Generated by ShadeSpace Professional Configurator',
    line2: 'Visit shadespace.com for more information',
  },
  sections: {
    showSummary: true,
    showMeasurements: true,
    showAnchorPoints: true,
    showHardwareBreakdown: true,
    showPriceBreakdown: true,
    showGuarantee: true,
    showPricingCallout: true,
  },
  paper: 'A4',
  layout: { density: 'comfortable', columns: 1 },
};

function mergeConfig(input: Partial<PdfTemplateConfig> | null | undefined): PdfTemplateConfig {
  const layoutInput = input?.layout || {};
  return {
    brand: { ...DEFAULT_CONFIG.brand, ...(input?.brand || {}) },
    header: { ...DEFAULT_CONFIG.header, ...(input?.header || {}) },
    footer: { ...DEFAULT_CONFIG.footer, ...(input?.footer || {}) },
    sections: { ...DEFAULT_CONFIG.sections, ...(input?.sections || {}) },
    paper: (input?.paper as 'A4' | 'Letter') || DEFAULT_CONFIG.paper,
    layout: {
      density: (layoutInput.density as PdfDensity) || DEFAULT_CONFIG.layout!.density,
      columns: (layoutInput.columns === 2 ? 2 : 1) as 1 | 2,
    },
  };
}

function normalizeBlocks(input: unknown): PdfBlock[] {
  if (!Array.isArray(input) || input.length === 0) return DEFAULT_BLOCKS.map((b) => ({ ...b, id: newBlockId() }));
  return input
    .filter((b) => b && typeof b === 'object')
    .map((raw) => {
      const b = raw as Partial<PdfBlock>;
      return {
        id: typeof b.id === 'string' && b.id ? b.id : newBlockId(),
        type: (b.type as BlockType) || 'customText',
        visible: b.visible !== false,
        props: (b.props && typeof b.props === 'object' ? b.props : {}) as Record<string, unknown>,
      };
    });
}

export const PdfStudio: React.FC = () => {
  const [templates, setTemplates] = useState<PdfTemplateRow[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [config, setConfig] = useState<PdfTemplateConfig>(DEFAULT_CONFIG);
  const [blocks, setBlocks] = useState<PdfBlock[]>(DEFAULT_BLOCKS);
  const [name, setName] = useState<string>('');
  const [selectedBlockId, setSelectedBlockId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ kind: 'ok' | 'err'; text: string } | null>(null);
  const [pane, setPane] = useState<'layout' | 'branding'>('layout');
  const [dataSource, setDataSource] = useState<'mock' | 'live'>('mock');
  const [liveQuotes, setLiveQuotes] = useState<LiveQuoteRow[]>([]);
  const [selectedQuoteId, setSelectedQuoteId] = useState<string>('');
  const [loadingQuotes, setLoadingQuotes] = useState(false);
  const [previewMode, setPreviewMode] = useState<'html' | 'pdf'>('html');
  const [pdfPreviewUrl, setPdfPreviewUrl] = useState<string>('');
  const [pdfPreviewLoading, setPdfPreviewLoading] = useState(false);
  const [pdfPreviewError, setPdfPreviewError] = useState<string | null>(null);

  const loadLiveQuotes = async () => {
    setLoadingQuotes(true);
    const { data, error } = await supabase
      .from('saved_quotes')
      .select('id, quote_reference, quote_name, customer_first_name, customer_last_name, customer_email, customer_reference, access_token, diagram_public_url, created_at, config_data, calculations_data')
      .order('created_at', { ascending: false })
      .limit(25);
    setLoadingQuotes(false);
    if (error) {
      setMessage({ kind: 'err', text: `Failed to load quotes: ${error.message}` });
      return;
    }
    const rows = (data || []) as unknown as LiveQuoteRow[];
    setLiveQuotes(rows);
    if (rows.length > 0 && !selectedQuoteId) setSelectedQuoteId(rows[0].id);
  };

  useEffect(() => {
    if (dataSource === 'live' && liveQuotes.length === 0) loadLiveQuotes();
  }, [dataSource]);

  const selectedQuote = useMemo(
    () => liveQuotes.find((q) => q.id === selectedQuoteId) || null,
    [liveQuotes, selectedQuoteId],
  );

  const loadTemplates = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('pdf_templates')
      .select('*')
      .order('created_at', { ascending: true });
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      setLoading(false);
      return;
    }
    const rows = ((data || []) as unknown as PdfTemplateRow[]).map((r) => ({
      ...r,
      blocks: normalizeBlocks((r as unknown as { blocks: unknown }).blocks),
    }));
    setTemplates(rows);
    const active = rows.find((r) => r.is_active) || rows[0];
    if (active) {
      setActiveId(active.id);
      setName(active.name);
      setConfig(mergeConfig(active.config));
      setBlocks(active.blocks);
      setSelectedBlockId(active.blocks[0]?.id ?? null);
    }
    setLoading(false);
  };

  useEffect(() => {
    loadTemplates();
  }, []);

  const handleSelect = (id: string) => {
    const row = templates.find((t) => t.id === id);
    if (!row) return;
    setActiveId(id);
    setName(row.name);
    setConfig(mergeConfig(row.config));
    setBlocks(row.blocks);
    setSelectedBlockId(row.blocks[0]?.id ?? null);
    setMessage(null);
  };

  const handleSave = async () => {
    if (!activeId) return;
    setSaving(true);
    setMessage(null);
    const { error } = await supabase
      .from('pdf_templates')
      .update({ name, config, blocks, updated_at: new Date().toISOString() })
      .eq('id', activeId);
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template saved.' });
    loadTemplates();
  };

  const handleSetActive = async () => {
    if (!activeId) return;
    setSaving(true);
    await supabase.from('pdf_templates').update({ is_active: false }).neq('id', activeId);
    const { error } = await supabase
      .from('pdf_templates')
      .update({ is_active: true })
      .eq('id', activeId);
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template activated.' });
    loadTemplates();
  };

  const handleDuplicate = async () => {
    const newName = `${name} (copy)`;
    setSaving(true);
    const { data, error } = await supabase
      .from('pdf_templates')
      .insert({ name: newName, is_active: false, config, blocks })
      .select()
      .single();
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template duplicated.' });
    await loadTemplates();
    if (data) setActiveId((data as PdfTemplateRow).id);
  };

  const handleResetBranding = () => {
    setConfig(DEFAULT_CONFIG);
  };

  const addBlock = (type: BlockType) => {
    const block: PdfBlock = { id: newBlockId(), type, visible: true, props: makeDefaultProps(type) };
    const idx = blocks.findIndex((b) => b.id === selectedBlockId);
    const next = [...blocks];
    next.splice(idx >= 0 ? idx + 1 : next.length, 0, block);
    setBlocks(next);
    setSelectedBlockId(block.id);
  };

  const removeBlock = (id: string) => {
    const next = blocks.filter((b) => b.id !== id);
    setBlocks(next);
    if (selectedBlockId === id) setSelectedBlockId(next[0]?.id ?? null);
  };

  const move = (id: string, dir: -1 | 1) => {
    const idx = blocks.findIndex((b) => b.id === id);
    if (idx < 0) return;
    const target = idx + dir;
    if (target < 0 || target >= blocks.length) return;
    const next = [...blocks];
    const [b] = next.splice(idx, 1);
    next.splice(target, 0, b);
    setBlocks(next);
  };

  const updateBlock = (id: string, patch: Partial<PdfBlock>) => {
    setBlocks(blocks.map((b) => (b.id === id ? { ...b, ...patch } : b)));
  };

  const updateBlockProp = (id: string, key: string, value: unknown) => {
    setBlocks(
      blocks.map((b) => (b.id === id ? { ...b, props: { ...b.props, [key]: value } } : b))
    );
  };

  const selected = useMemo(() => blocks.find((b) => b.id === selectedBlockId) || null, [blocks, selectedBlockId]);
  const liveData = dataSource === 'live' ? selectedQuote : null;
  const previewHtml = useMemo(() => buildPreview(config, blocks, liveData), [config, blocks, liveData]);

  const renderPdfPreview = async () => {
    setPdfPreviewLoading(true);
    setPdfPreviewError(null);
    try {
      const sourceConfig = liveData?.config_data || (buildSampleConfig() as ConfiguratorState);
      const sourceCalc = liveData?.calculations_data || (buildSampleCalc() as ShadeCalculations);
      const url = await generatePdfFromBlocks(
        sourceConfig,
        sourceCalc,
        blocks,
        {
          layout: {
            density: config.layout?.density,
            columns: config.layout?.columns,
          },
          chrome: {
            brand: config.brand,
            header: config.header,
            footer: config.footer,
            paper: config.paper,
          },
          customer: liveData ? {
            firstName: liveData.customer_first_name || undefined,
            lastName: liveData.customer_last_name || undefined,
            email: liveData.customer_email || undefined,
            quoteName: liveData.quote_name || undefined,
            customerReference: liveData.customer_reference || undefined,
            quoteUrl: `https://shadespace.com/pages/shade-sail-configurator?quote=${liveData.id}&token=${encodeURIComponent(liveData.access_token)}`,
          } : undefined,
          returnBlob: true,
        },
      );
      if (typeof url === 'string') setPdfPreviewUrl(url);
    } catch (err) {
      setPdfPreviewError(err instanceof Error ? err.message : String(err));
    } finally {
      setPdfPreviewLoading(false);
    }
  };

  useEffect(() => {
    if (previewMode !== 'pdf') return;
    renderPdfPreview();
    return () => {
      if (pdfPreviewUrl) URL.revokeObjectURL(pdfPreviewUrl);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    previewMode,
    config.layout?.density,
    config.layout?.columns,
    liveData?.id,
    blocks,
    config.brand,
    config.header,
    config.footer,
    config.paper,
  ]);

  if (loading) {
    return <Card className="p-6">Loading templates...</Card>;
  }

  return (
    <div className="space-y-6">
      <Card className="p-4 sm:p-6 border border-gray-200">
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-xs font-medium text-gray-600 mb-1">Template</label>
            <select
              value={activeId || ''}
              onChange={(e) => handleSelect(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-lime-500 focus:border-lime-500"
            >
              {templates.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name} {t.is_active ? '(active)' : ''}
                </option>
              ))}
            </select>
          </div>
          <div className="flex-1 min-w-[200px]">
            <label className="block text-xs font-medium text-gray-600 mb-1">Name</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-lime-500 focus:border-lime-500"
            />
          </div>
          <div className="flex gap-2 pt-5">
            <Button onClick={handleSave} disabled={saving}>Save</Button>
            <Button onClick={handleSetActive} disabled={saving} variant="outline">Set Active</Button>
            <Button onClick={handleDuplicate} disabled={saving} variant="outline">Duplicate</Button>
          </div>
        </div>
        {message && (
          <div
            className={`mt-3 text-sm px-3 py-2 rounded ${
              message.kind === 'ok'
                ? 'bg-lime-50 text-lime-800 border border-lime-200'
                : 'bg-red-50 text-red-800 border border-red-200'
            }`}
          >
            {message.text}
          </div>
        )}
        <div className="mt-4 border-t border-gray-200 pt-3">
          <div className="text-xs font-semibold text-gray-700 mb-2">Preview data source</div>
          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() => setDataSource('mock')}
              className={`px-3 py-1.5 text-sm rounded-lg border ${dataSource === 'mock' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'}`}
            >
              Mock sample data
            </button>
            <button
              type="button"
              onClick={() => setDataSource('live')}
              className={`px-3 py-1.5 text-sm rounded-lg border ${dataSource === 'live' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'}`}
            >
              Live saved quote
            </button>
            {dataSource === 'live' && (
              <>
                <select
                  value={selectedQuoteId}
                  onChange={(e) => setSelectedQuoteId(e.target.value)}
                  disabled={loadingQuotes}
                  className="flex-1 min-w-[240px] border border-gray-300 rounded-lg px-3 py-1.5 text-sm focus:ring-2 focus:ring-lime-500 focus:border-lime-500"
                >
                  {loadingQuotes && <option>Loading...</option>}
                  {!loadingQuotes && liveQuotes.length === 0 && <option value="">No saved quotes found</option>}
                  {liveQuotes.map((q) => {
                    const name = [q.customer_first_name, q.customer_last_name].filter(Boolean).join(' ').trim() || q.customer_email || 'Anonymous';
                    const ref = q.quote_reference || q.id.slice(0, 8);
                    const dt = new Date(q.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
                    return (
                      <option key={q.id} value={q.id}>{ref} \u2014 {name} ({dt})</option>
                    );
                  })}
                </select>
                <button
                  type="button"
                  onClick={loadLiveQuotes}
                  disabled={loadingQuotes}
                  className="px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50"
                >
                  Refresh
                </button>
              </>
            )}
          </div>
          {dataSource === 'live' && selectedQuote && (
            <div className="mt-2 text-xs text-gray-500">
              Previewing with <strong className="text-gray-700">{selectedQuote.quote_reference || selectedQuote.id.slice(0, 8)}</strong>
              {selectedQuote.config_data?.currency ? ` \u2014 ${selectedQuote.config_data.currency}` : ''}
              {selectedQuote.diagram_public_url ? ' \u2022 diagram available' : ' \u2022 no diagram'}
            </div>
          )}
        </div>

        <div className="mt-4 flex gap-2">
          <button
            type="button"
            onClick={() => setPane('layout')}
            className={`px-3 py-1.5 text-sm rounded-lg border ${pane === 'layout' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600'}`}
          >
            Layout & Blocks
          </button>
          <button
            type="button"
            onClick={() => setPane('branding')}
            className={`px-3 py-1.5 text-sm rounded-lg border ${pane === 'branding' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600'}`}
          >
            Branding & Text
          </button>
        </div>
      </Card>

      <div className="grid grid-cols-1 xl:grid-cols-[280px_1fr_320px] gap-6">
        {pane === 'layout' ? (
          <Card className="p-3 border border-gray-200">
            <div className="text-xs font-semibold text-gray-700 mb-2">Blocks (drag order with arrows)</div>
            <div className="space-y-1">
              {blocks.map((b) => (
                <div
                  key={b.id}
                  className={`flex items-center gap-1 rounded border px-2 py-1.5 text-sm cursor-pointer ${
                    selectedBlockId === b.id ? 'border-lime-500 bg-lime-50' : 'border-gray-200 hover:bg-gray-50'
                  }`}
                  onClick={() => setSelectedBlockId(b.id)}
                >
                  <button
                    type="button"
                    className="text-gray-400 hover:text-gray-700"
                    onClick={(e) => {
                      e.stopPropagation();
                      move(b.id, -1);
                    }}
                    aria-label="Move up"
                  >
                    {'\u25B2'}
                  </button>
                  <button
                    type="button"
                    className="text-gray-400 hover:text-gray-700"
                    onClick={(e) => {
                      e.stopPropagation();
                      move(b.id, 1);
                    }}
                    aria-label="Move down"
                  >
                    {'\u25BC'}
                  </button>
                  <span className={`flex-1 truncate ${b.visible ? '' : 'line-through text-gray-400'}`}>
                    {BLOCK_LABELS[b.type]}
                  </span>
                  <button
                    type="button"
                    className="text-gray-400 hover:text-gray-700"
                    onClick={(e) => {
                      e.stopPropagation();
                      updateBlock(b.id, { visible: !b.visible });
                    }}
                    aria-label="Toggle visibility"
                    title={b.visible ? 'Hide' : 'Show'}
                  >
                    {b.visible ? 'o' : '-'}
                  </button>
                  <button
                    type="button"
                    className="text-red-400 hover:text-red-700"
                    onClick={(e) => {
                      e.stopPropagation();
                      removeBlock(b.id);
                    }}
                    aria-label="Delete"
                  >
                    x
                  </button>
                </div>
              ))}
            </div>
            <div className="mt-4 border-t border-gray-200 pt-3">
              <div className="text-xs font-semibold text-gray-700 mb-2">Add block</div>
              <div className="grid grid-cols-2 gap-1">
                {(Object.keys(BLOCK_LABELS) as BlockType[]).map((t) => (
                  <button
                    key={t}
                    type="button"
                    onClick={() => addBlock(t)}
                    className="px-2 py-1.5 text-xs border border-gray-300 rounded hover:bg-gray-50 text-left"
                  >
                    + {BLOCK_LABELS[t]}
                  </button>
                ))}
              </div>
            </div>
          </Card>
        ) : (
          <Card className="p-4 border border-gray-200 space-y-6">
            <Section title="Branding">
              <ColorRow label="Primary" value={config.brand.primaryColor} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, primaryColor: v } })} />
              <ColorRow label="Accent" value={config.brand.accentColor} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, accentColor: v } })} />
              <ColorRow label="Accent Dark" value={config.brand.accentDark} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, accentDark: v } })} />
              <ColorRow label="Text" value={config.brand.textColor} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, textColor: v } })} />
              <ColorRow label="Muted" value={config.brand.mutedColor} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, mutedColor: v } })} />
              <ColorRow label="Background" value={config.brand.backgroundColor} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, backgroundColor: v } })} />
              <TextRow label="Logo URL" value={config.brand.logoUrl} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, logoUrl: v } })} placeholder="https://..." />
              <TextRow label="Font family" value={config.brand.fontFamily} onChange={(v) => setConfig({ ...config, brand: { ...config.brand, fontFamily: v } })} />
            </Section>
            <Section title="Header">
              <TextRow label="Title" value={config.header.title} onChange={(v) => setConfig({ ...config, header: { ...config.header, title: v } })} />
              <TextRow label="Tagline" value={config.header.tagline} onChange={(v) => setConfig({ ...config, header: { ...config.header, tagline: v } })} />
            </Section>
            <Section title="Footer">
              <TextRow label="Line 1" value={config.footer.line1} onChange={(v) => setConfig({ ...config, footer: { ...config.footer, line1: v } })} />
              <TextRow label="Line 2" value={config.footer.line2} onChange={(v) => setConfig({ ...config, footer: { ...config.footer, line2: v } })} />
            </Section>
            <Section title="Layout density">
              <div className="flex flex-wrap gap-2">
                {(['comfortable', 'compact', 'ultra'] as const).map((d) => (
                  <button
                    key={d}
                    type="button"
                    onClick={() => setConfig({ ...config, layout: { density: d, columns: config.layout?.columns || 1 } })}
                    className={`px-3 py-1.5 rounded-lg border text-sm capitalize ${
                      (config.layout?.density || 'comfortable') === d ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    {d}
                  </button>
                ))}
              </div>
              <p className="text-[11px] text-gray-500 mt-1">Comfortable matches the original spacing. Compact tightens fonts and gaps. Ultra is the densest setting for long quotes.</p>
              <div className="mt-3 flex gap-2">
                {([1, 2] as const).map((c) => (
                  <button
                    key={c}
                    type="button"
                    onClick={() => setConfig({ ...config, layout: { density: config.layout?.density || 'comfortable', columns: c } })}
                    className={`px-3 py-1.5 rounded-lg border text-sm ${
                      (config.layout?.columns || 1) === c ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    {c} column{c > 1 ? 's' : ''}
                  </button>
                ))}
              </div>
              <p className="text-[11px] text-gray-500 mt-1">Two columns is applied to the Configuration Summary block to reduce vertical space.</p>
            </Section>
            <Section title="Paper">
              <div className="flex gap-2">
                {(['A4', 'Letter'] as const).map((p) => (
                  <button
                    key={p}
                    type="button"
                    onClick={() => setConfig({ ...config, paper: p })}
                    className={`px-3 py-1.5 rounded-lg border text-sm ${
                      config.paper === p ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    {p}
                  </button>
                ))}
              </div>
            </Section>
            <Button onClick={handleResetBranding} variant="outline">Reset branding to defaults</Button>
          </Card>
        )}

        <Card className="p-0 border border-gray-200 overflow-hidden">
          <div className="px-4 py-3 border-b border-gray-200 bg-gray-50 flex items-center justify-between gap-3">
            <div className="text-sm font-semibold text-gray-700">Live preview</div>
            <div className="flex gap-1">
              <button
                type="button"
                onClick={() => setPreviewMode('html')}
                className={`px-3 py-1.5 text-xs rounded border ${previewMode === 'html' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'}`}
              >
                HTML mockup
              </button>
              <button
                type="button"
                onClick={() => setPreviewMode('pdf')}
                className={`px-3 py-1.5 text-xs rounded border ${previewMode === 'pdf' ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'}`}
              >
                Rendered PDF
              </button>
              {previewMode === 'pdf' && (
                <button
                  type="button"
                  onClick={renderPdfPreview}
                  disabled={pdfPreviewLoading}
                  className="px-3 py-1.5 text-xs rounded border border-gray-300 text-gray-600 hover:bg-gray-50 disabled:opacity-50"
                >
                  {pdfPreviewLoading ? 'Rendering...' : 'Refresh'}
                </button>
              )}
            </div>
          </div>
          {previewMode === 'html' ? (
            <iframe
              title="pdf-preview"
              srcDoc={previewHtml}
              className="w-full bg-white"
              style={{ height: '820px', border: 'none' }}
            />
          ) : (
            <div className="w-full bg-gray-100" style={{ height: '820px' }}>
              {pdfPreviewError ? (
                <div className="p-4 text-sm text-red-700 bg-red-50 border border-red-200 m-4 rounded">
                  Failed to render PDF: {pdfPreviewError}
                </div>
              ) : pdfPreviewUrl ? (
                <iframe
                  title="rendered-pdf"
                  src={`${pdfPreviewUrl}#view=FitH`}
                  className="w-full h-full bg-white"
                  style={{ border: 'none' }}
                />
              ) : (
                <div className="p-6 text-sm text-gray-500">{pdfPreviewLoading ? 'Generating PDF...' : 'PDF preview not loaded.'}</div>
              )}
              <div className="px-3 py-2 text-[11px] text-gray-500 bg-gray-50 border-t border-gray-200">
                Tip: scroll inside the PDF viewer to see all pages. Larger quotes (more corners and dimensions) will produce additional pages here.
              </div>
            </div>
          )}
        </Card>

        {pane === 'layout' && (
          <Card className="p-4 border border-gray-200">
            <div className="text-xs font-semibold text-gray-700 mb-2">Block properties</div>
            {!selected ? (
              <div className="text-sm text-gray-500">Select a block to edit its properties.</div>
            ) : (
              <BlockPropsEditor
                block={selected}
                onProp={(k, v) => updateBlockProp(selected.id, k, v)}
                onToggle={(v) => updateBlock(selected.id, { visible: v })}
              />
            )}
          </Card>
        )}
      </div>
    </div>
  );
};

const BlockPropsEditor: React.FC<{
  block: PdfBlock;
  onProp: (k: string, v: unknown) => void;
  onToggle: (v: boolean) => void;
}> = ({ block, onProp, onToggle }) => {
  const props = block.props || {};
  return (
    <div className="space-y-3">
      <div className="text-sm font-semibold text-gray-800">{BLOCK_LABELS[block.type]}</div>
      <label className="flex items-center gap-2 text-sm text-gray-700">
        <input
          type="checkbox"
          checked={block.visible}
          onChange={(e) => onToggle(e.target.checked)}
          className="rounded border-gray-300 text-lime-600 focus:ring-lime-500"
        />
        Visible
      </label>

      {block.type !== 'pageBreak' && (
        <div>
          <label className="block text-xs font-semibold text-gray-700 mb-1">Column placement</label>
          <div className="flex gap-1">
            {(['full', 'left', 'right'] as const).map((c) => (
              <button
                key={c}
                type="button"
                onClick={() => onProp('column', c)}
                className={`flex-1 px-2 py-1.5 text-xs rounded border capitalize ${
                  ((props.column as string) || 'full') === c ? 'border-lime-500 bg-lime-50 text-lime-800' : 'border-gray-300 text-gray-600 hover:bg-gray-50'
                }`}
              >
                {c === 'full' ? 'Full width' : `${c} col`}
              </button>
            ))}
          </div>
          <p className="text-[11px] text-gray-500 mt-1">Consecutive Left + Right blocks render side-by-side. Full-width resets to a single column.</p>
        </div>
      )}

      <div>
        <label className="block text-xs font-semibold text-gray-700 mb-1">Density override</label>
        <select
          value={String(props.densityOverride ?? '')}
          onChange={(e) => onProp('densityOverride', e.target.value || undefined)}
          className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
        >
          <option value="">Inherit from template</option>
          <option value="comfortable">Comfortable</option>
          <option value="compact">Compact</option>
          <option value="ultra">Ultra</option>
        </select>
      </div>

      {DYNAMIC_TYPES.includes(block.type) && (
        <TextRow
          label="Title"
          value={String(props.title ?? '')}
          onChange={(v) => onProp('title', v)}
        />
      )}

      {block.type === 'diagramImage' && (
        <div>
          <label className="block text-xs text-gray-600 mb-1">Max width (px)</label>
          <input
            type="number"
            value={Number(props.maxWidth ?? 520)}
            onChange={(e) => onProp('maxWidth', Number(e.target.value) || 520)}
            className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
          />
        </div>
      )}

      {block.type === 'resumeButton' && (
        <TextRow
          label="Button label"
          value={String(props.label ?? 'Open My Saved Quote')}
          onChange={(v) => onProp('label', v)}
        />
      )}

      {block.type === 'customText' && (
        <>
          <TextRow label="Heading" value={String(props.heading ?? '')} onChange={(v) => onProp('heading', v)} />
          <div>
            <label className="block text-xs text-gray-600 mb-1">Body</label>
            <textarea
              value={String(props.body ?? '')}
              onChange={(e) => onProp('body', e.target.value)}
              rows={5}
              className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm font-mono"
            />
          </div>
          <div>
            <label className="block text-xs text-gray-600 mb-1">Align</label>
            <select
              value={String(props.align ?? 'left')}
              onChange={(e) => onProp('align', e.target.value)}
              className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
            >
              <option value="left">Left</option>
              <option value="center">Center</option>
              <option value="right">Right</option>
            </select>
          </div>
        </>
      )}

      {block.type === 'customImage' && (
        <>
          <TextRow label="Image URL" value={String(props.url ?? '')} onChange={(v) => onProp('url', v)} placeholder="https://..." />
          <TextRow label="Alt" value={String(props.alt ?? '')} onChange={(v) => onProp('alt', v)} />
          <div>
            <label className="block text-xs text-gray-600 mb-1">Width (px)</label>
            <input
              type="number"
              value={Number(props.width ?? 400)}
              onChange={(e) => onProp('width', Number(e.target.value) || 0)}
              className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
            />
          </div>
        </>
      )}

      {block.type === 'customHtml' && (
        <div>
          <label className="block text-xs text-gray-600 mb-1">HTML (scripts and event handlers stripped)</label>
          <textarea
            value={String(props.html ?? '')}
            onChange={(e) => onProp('html', e.target.value)}
            rows={8}
            className="w-full border border-gray-300 rounded px-2 py-1.5 text-xs font-mono"
          />
        </div>
      )}

      {block.type === 'spacer' && (
        <div>
          <label className="block text-xs text-gray-600 mb-1">Height (px)</label>
          <input
            type="number"
            value={Number(props.height ?? 16)}
            onChange={(e) => onProp('height', Number(e.target.value) || 0)}
            className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
          />
        </div>
      )}

      {block.type === 'divider' && (
        <div>
          <label className="block text-xs text-gray-600 mb-1">Thickness (px)</label>
          <input
            type="number"
            value={Number(props.thickness ?? 1)}
            onChange={(e) => onProp('thickness', Number(e.target.value) || 1)}
            className="w-full border border-gray-300 rounded px-2 py-1.5 text-sm"
          />
        </div>
      )}
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div>
    <h3 className="text-sm font-semibold text-gray-800 mb-2">{title}</h3>
    <div className="space-y-2">{children}</div>
  </div>
);

const ColorRow: React.FC<{ label: string; value: string; onChange: (v: string) => void }> = ({ label, value, onChange }) => (
  <div className="flex items-center gap-3">
    <label className="w-28 text-xs text-gray-600">{label}</label>
    <input type="color" value={value} onChange={(e) => onChange(e.target.value)} className="h-8 w-10 border border-gray-300 rounded" />
    <input type="text" value={value} onChange={(e) => onChange(e.target.value)} className="flex-1 border border-gray-300 rounded px-2 py-1.5 text-sm font-mono" />
  </div>
);

const TextRow: React.FC<{ label: string; value: string; onChange: (v: string) => void; placeholder?: string }> = ({ label, value, onChange, placeholder }) => (
  <div className="flex items-center gap-3">
    <label className="w-28 text-xs text-gray-600">{label}</label>
    <input type="text" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="flex-1 border border-gray-300 rounded px-2 py-1.5 text-sm" />
  </div>
);

function buildSampleConfig(): Partial<ConfiguratorState> {
  return {
    step: 6,
    fabricType: 'monotec370',
    fabricColor: 'Domino Black',
    edgeType: 'webbing',
    corners: 4,
    unit: 'metric',
    measurementOption: 'exact',
    points: [{ x: 0, y: 0 }, { x: 4000, y: 0 }, { x: 4000, y: 3500 }, { x: 0, y: 3500 }],
    measurements: { AB: 4000, BC: 3500, CD: 4200, DA: 3300, AC: 5400, BD: 5200 },
    fixingHeights: [2400, 2400, 2200, 2200],
    fixingTypes: ['post', 'post', 'building', 'building'],
    eyeOrientations: ['horizontal', 'horizontal', 'vertical', 'vertical'],
    fixingPointsInstalled: false,
    currency: 'NZD',
    hardwareSelectionMode: 'standard',
  };
}

function buildSampleCalc(): Partial<ShadeCalculations> {
  return {
    area: 14.7,
    perimeter: 15000,
    fabricCost: 600,
    edgeCost: 0,
    hardwareCost: 200,
    totalPrice: 1299,
    webbingWidth: 50,
    totalWeightGrams: 4400,
    hardwareBreakdown: {
      mode: 'standard',
      subtotalNzd: 200,
      perCornerNzd: [50, 50, 50, 50],
      sailOnlyPriceNzd: 1099,
      hardwareOnlyPriceNzd: 200,
    },
  };
}

type HtmlDensityPreset = {
  body: number;
  title: number;
  tagline: number;
  h2: number;
  row: number;
  rowPad: number;
  small: number;
  priceLg: number;
  sectionMargin: number;
  twoColGap: number;
};

const HTML_DENSITY_PRESETS: Record<'comfortable' | 'compact' | 'ultra', HtmlDensityPreset> = {
  comfortable: { body: 14, title: 22, tagline: 12, h2: 16, row: 13, rowPad: 6, small: 11, priceLg: 22, sectionMargin: 20, twoColGap: 16 },
  compact:     { body: 13, title: 18, tagline: 11, h2: 14, row: 12, rowPad: 4, small: 10, priceLg: 18, sectionMargin: 14, twoColGap: 12 },
  ultra:       { body: 12, title: 16, tagline: 10, h2: 12, row: 11, rowPad: 3, small: 9,  priceLg: 16, sectionMargin: 10, twoColGap: 8 },
};

function densityCss(scope: string, p: HtmlDensityPreset, brand: PdfTemplateConfig['brand']): string {
  return `
    ${scope} { font-size:${p.body}px; }
    ${scope} h2 { font-size:${p.h2}px; color:${brand.primaryColor}; border-bottom:2px solid ${brand.accentColor}; padding-bottom:${Math.max(2, Math.round(p.rowPad - 1))}px; margin:${p.sectionMargin}px 0 ${Math.max(6, Math.round(p.sectionMargin / 2))}px; }
    ${scope} .row { display:flex; justify-content:space-between; padding:${p.rowPad}px 0; border-bottom:1px solid #E5E7EB; font-size:${p.row}px; }
    ${scope} .callout { margin-top:${p.sectionMargin}px; padding:${Math.max(10, p.rowPad * 2 + 6)}px; border-radius:12px; background:${brand.primaryColor}; color:#fff; text-align:center; }
    ${scope} .callout .price { font-size:${p.priceLg}px; font-weight:700; color:${brand.accentColor}; }
    ${scope} .guarantee { margin-top:${p.sectionMargin}px; padding:${Math.max(10, p.rowPad * 2 + 6)}px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${brand.accentColor} 20%); border:2px solid ${brand.accentDark}; color:${brand.primaryColor}; font-size:${p.row}px; }
  `;
}

function buildPreview(cfg: PdfTemplateConfig, blocks: PdfBlock[], live: LiveQuoteRow | null): string {
  const b = cfg.brand;
  const baseDensity = (cfg.layout?.density || 'comfortable') as 'comfortable' | 'compact' | 'ultra';
  const basePreset = HTML_DENSITY_PRESETS[baseDensity];
  const overrideStyles: string[] = [];
  for (const d of ['comfortable', 'compact', 'ultra'] as const) {
    overrideStyles.push(densityCss(`.density-${d}`, HTML_DENSITY_PRESETS[d], b));
  }
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
    body { margin:0; padding:24px; background:${b.backgroundColor}; font-family:${b.fontFamily}; color:${b.textColor}; font-size:${basePreset.body}px; }
    .header { display:flex; align-items:center; gap:12px; padding:16px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${b.accentColor} 100%); border:2px solid ${b.accentDark}; margin-bottom:16px; }
    .logo-img { max-height:40px; max-width:180px; object-fit:contain; }
    .title { font-size:${basePreset.title}px; font-weight:700; color:${b.primaryColor}; margin:0; }
    .tagline { font-size:${basePreset.tagline}px; color:${b.accentDark}; margin:4px 0 0 0; }
    h2 { font-size:${basePreset.h2}px; color:${b.primaryColor}; border-bottom:2px solid ${b.accentColor}; padding-bottom:${Math.max(2, basePreset.rowPad - 1)}px; margin:${basePreset.sectionMargin}px 0 ${Math.max(6, Math.round(basePreset.sectionMargin / 2))}px; }
    .row { display:flex; justify-content:space-between; padding:${basePreset.rowPad}px 0; border-bottom:1px solid #E5E7EB; font-size:${basePreset.row}px; }
    .muted { color:${b.mutedColor}; }
    .val { color:${b.textColor}; font-weight:600; }
    .callout { margin-top:${basePreset.sectionMargin}px; padding:${Math.max(10, basePreset.rowPad * 2 + 6)}px; border-radius:12px; background:${b.primaryColor}; color:#fff; text-align:center; }
    .callout .price { font-size:${basePreset.priceLg}px; font-weight:700; color:${b.accentColor}; }
    .guarantee { margin-top:${basePreset.sectionMargin}px; padding:${Math.max(10, basePreset.rowPad * 2 + 6)}px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${b.accentColor} 20%); border:2px solid ${b.accentDark}; color:${b.primaryColor}; font-size:${basePreset.row}px; }
    .footer { margin-top:24px; text-align:center; font-size:${basePreset.small}px; color:${b.mutedColor}; }
    hr { border:none; border-top:1px solid ${b.mutedColor}; margin:8px 0; opacity:0.4; }
    .two-col { display:grid; grid-template-columns:1fr 1fr; gap:${basePreset.twoColGap}px; align-items:start; margin-top:4px; }
    .two-col > .col { min-width:0; }
    .two-col h2 { margin-top:8px; }
    .block-wrap { display:block; }
    ${overrideStyles.join('\n')}
  </style></head><body>
    <div class="header">
      ${b.logoUrl ? `<img class="logo-img" src="${escapeHtml(b.logoUrl)}" alt="logo" />` : ''}
      <div>
        <h1 class="title">${escapeHtml(cfg.header.title)}</h1>
        <p class="tagline">${escapeHtml(cfg.header.tagline)}</p>
      </div>
    </div>
    ${renderGroupedBlocks(blocks.filter((x) => x.visible), cfg, live)}
    <div class="footer">
      <div>${escapeHtml(cfg.footer.line1)}</div>
      <div>${escapeHtml(cfg.footer.line2)}</div>
    </div>
  </body></html>`;
}

function densityForBlock(block: PdfBlock, cfg: PdfTemplateConfig): 'comfortable' | 'compact' | 'ultra' {
  const o = (block.props?.densityOverride as string | undefined) || undefined;
  if (o === 'comfortable' || o === 'compact' || o === 'ultra') return o;
  return (cfg.layout?.density || 'comfortable') as 'comfortable' | 'compact' | 'ultra';
}

function wrapBlock(block: PdfBlock, cfg: PdfTemplateConfig, live: LiveQuoteRow | null): string {
  const d = densityForBlock(block, cfg);
  return `<div class="block-wrap density-${d}">${renderSampleBlock(block, cfg, live)}</div>`;
}

function renderGroupedBlocks(blocks: PdfBlock[], cfg: PdfTemplateConfig, live: LiveQuoteRow | null): string {
  const out: string[] = [];
  let leftBuf: PdfBlock[] = [];
  let rightBuf: PdfBlock[] = [];
  const flush = () => {
    if (leftBuf.length === 0 && rightBuf.length === 0) return;
    const leftHtml = leftBuf.map((x) => wrapBlock(x, cfg, live)).join('');
    const rightHtml = rightBuf.map((x) => wrapBlock(x, cfg, live)).join('');
    out.push(`<div class="two-col"><div class="col">${leftHtml}</div><div class="col">${rightHtml}</div></div>`);
    leftBuf = [];
    rightBuf = [];
  };
  for (const block of blocks) {
    const col = getBlockColumn(block);
    if (col === 'full') {
      flush();
      out.push(wrapBlock(block, cfg, live));
    } else if (col === 'left') {
      leftBuf.push(block);
    } else {
      rightBuf.push(block);
    }
  }
  flush();
  return out.join('');
}

function renderSampleBlock(block: PdfBlock, cfg: PdfTemplateConfig, live: LiveQuoteRow | null): string {
  const p = block.props || {};
  const title = (p.title as string) || BLOCK_LABELS[block.type];
  const cfgData = live?.config_data;
  const calc = live?.calculations_data;
  const currency = cfgData?.currency || 'NZD';
  const total = calc?.totalPrice ?? 650;
  const fabricLabel = cfgData?.fabricType || 'Monotec 370';
  const fabricColor = cfgData?.fabricColor || 'Domino Black';
  const corners = cfgData?.corners ?? 4;
  const unit: 'metric' | 'imperial' = cfgData?.unit || 'metric';
  switch (block.type) {
    case 'summary':
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">Fabric Material</span><span class="val">${escapeHtml(fabricLabel)}</span></div>
        <div class="row"><span class="muted">Fabric Color</span><span class="val">${escapeHtml(fabricColor)}</span></div>
        <div class="row"><span class="muted">Corners</span><span class="val">${corners}</span></div>
        <div class="row"><span class="muted">Total Area</span><span class="val">${formatAreaPreview((calc?.area || 12.5) * 1000000, unit)}</span></div>
        <div class="row"><span class="muted">Edge Reinforcement</span><span class="val">${cfgData?.edgeType === 'webbing' ? 'Webbing Reinforced' : cfgData?.edgeType === 'cabled' ? 'Cabled Edge' : 'Webbing Reinforced'}</span></div>`;
    case 'measurements': {
      if (cfgData && cfgData.measurements) {
        const edges: string[] = [];
        for (let i = 0; i < corners; i++) {
          const next = (i + 1) % corners;
          const key = `${String.fromCharCode(65 + i)}${String.fromCharCode(65 + next)}`;
          const mm = cfgData.measurements[key];
          if (mm) edges.push(`<div class="row"><span class="muted">Edge ${key.charAt(0)} to ${key.charAt(1)}</span><span class="val">${formatMeasurementPreview(mm, unit)}</span></div>`);
        }
        const diagonalRows: string[] = [];
        for (const key of getDiagonalKeysForCorners(corners)) {
          const mm = cfgData.measurements[key];
          if (mm) diagonalRows.push(`<div class="row"><span class="muted">Diagonal ${key.charAt(0)} to ${key.charAt(1)}</span><span class="val">${formatMeasurementPreview(mm, unit)}</span></div>`);
        }
        const edgesBlock = `<div style="margin-bottom:10px;"><div style="font-weight:700;color:${cfg.brand.accentDark};font-size:12px;margin-bottom:4px;">Edge Lengths</div>${edges.join('') || '<div class="row"><span class="muted">No edge measurements</span></div>'}</div>`;
        const diagonalsBlock = diagonalRows.length > 0
          ? `<div><div style="font-weight:700;color:${cfg.brand.accentDark};font-size:12px;margin-bottom:4px;">Diagonal Lengths</div>${diagonalRows.join('')}</div>`
          : '';
        return `<h2>${escapeHtml(title)}</h2>${edgesBlock}${diagonalsBlock}`;
      }
      return `<h2>${escapeHtml(title)}</h2>
        <div style="font-weight:700;color:${cfg.brand.accentDark};font-size:12px;margin-bottom:4px;">Edge Lengths</div>
        <div class="row"><span class="muted">Edge A to B</span><span class="val">4000mm</span></div>
        <div class="row"><span class="muted">Edge B to C</span><span class="val">3500mm</span></div>
        <div class="row"><span class="muted">Edge C to D</span><span class="val">4200mm</span></div>
        <div class="row"><span class="muted">Edge D to A</span><span class="val">3300mm</span></div>
        <div style="font-weight:700;color:${cfg.brand.accentDark};font-size:12px;margin:10px 0 4px;">Diagonal Lengths</div>
        <div class="row"><span class="muted">Diagonal A to C</span><span class="val">5400mm</span></div>
        <div class="row"><span class="muted">Diagonal B to D</span><span class="val">5200mm</span></div>`;
    }
    case 'anchorPoints': {
      if (cfgData && Array.isArray(cfgData.fixingHeights)) {
        const rows = cfgData.fixingHeights.slice(0, corners).map((h, i) => {
          const letter = String.fromCharCode(65 + i);
          const t = cfgData.fixingTypes?.[i] || 'post';
          const o = cfgData.eyeOrientations?.[i] || 'horizontal';
          return `<div class="row"><span class="muted">Corner ${letter}</span><span class="val">${formatMeasurementPreview(h || 0, unit)}, ${t}, ${o} eye</span></div>`;
        }).join('');
        return `<h2>${escapeHtml(title)}</h2>${rows}`;
      }
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">Corner A</span><span class="val">2400mm, post</span></div>`;
    }
    case 'hardwareBreakdown': {
      const hwMode: 'standard' | 'manual' | 'none' =
        cfgData?.hardwareSelectionMode ?? (cfgData?.measurementOption === 'adjust' ? 'standard' : 'none');
      if (hwMode === 'none') {
        return `<h2>${escapeHtml(title)}</h2><div class="row"><span class="muted">No tensioning hardware included with this order.</span></div>`;
      }
      if (hwMode === 'standard') {
        return `<h2>${escapeHtml(title)}</h2>
          <div class="row"><span class="muted">Hardware Tensioning Kit (${corners}-corner pack)</span><span class="val" style="color:#307C31;">Included</span></div>
          <div style="font-size:11px;color:${cfg.brand.mutedColor};padding:4px 0 0;">Pack contents are listed in the Bill of Materials block.</div>`;
      }
      const cornerHw = (cfgData as { cornerHardware?: Record<number, Array<{ name: string; sku?: string; qty: number; livePrice?: number; livePriceCurrency?: string }>> })?.cornerHardware;
      if (cornerHw) {
        const rows: string[] = [];
        for (let i = 0; i < corners; i++) {
          const letter = String.fromCharCode(65 + i);
          const lines = cornerHw[i] || [];
          const cornerTotal = lines.reduce((sum, l) => {
            const live = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice : 0;
            return sum + live * l.qty;
          }, 0);
          rows.push(`<div style="padding:8px 0;border-bottom:1px solid #E5E7EB;">
            <div style="display:flex;justify-content:space-between;font-weight:700;">
              <span>Corner ${letter}</span><span>${formatCurrencyPreview(cornerTotal, currency)}</span>
            </div>
            ${lines.length === 0 ? `<div style="padding-left:12px;font-size:11px;color:${cfg.brand.mutedColor};">No hardware selected</div>` : lines.map(l => {
              const skuPart = l.sku ? ` (${l.sku})` : '';
              const lineLive = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice * l.qty : 0;
              return `<div style="display:flex;justify-content:space-between;padding-left:12px;font-size:11px;color:${cfg.brand.mutedColor};">
                <span>${escapeHtml(l.qty)}x ${escapeHtml(l.name)}${escapeHtml(skuPart)}</span>
                <span>${formatCurrencyPreview(lineLive, currency)}</span>
              </div>`;
            }).join('')}
          </div>`);
        }
        return `<h2>${escapeHtml(title)}</h2>${rows.join('')}`;
      }
      return `<h2>${escapeHtml(title)}</h2>
        <div style="padding:8px 0;border-bottom:1px solid #E5E7EB;">
          <div style="display:flex;justify-content:space-between;font-weight:700;"><span>Corner A</span><span>${formatCurrencyPreview(0, currency)}</span></div>
          <div style="padding-left:12px;font-size:11px;color:${cfg.brand.mutedColor};">No hardware selected</div>
        </div>`;
    }
    case 'priceBreakdown':
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">Shade sail</span><span class="val">${formatCurrencyPreview(total - 70, currency)}</span></div>
        <div class="row"><span class="val">Total</span><span class="val">${formatCurrencyPreview(total, currency)}</span></div>`;
    case 'guarantee':
      return `<div class="guarantee"><div style="font-weight:700;margin-bottom:6px;">${escapeHtml(title)}</div>
        <div style="font-size:12px;">15-year Fabric &amp; Workmanship Warranty &middot; Weather-resistant materials &middot; Free worldwide shipping</div></div>`;
    case 'pricingCallout':
      return `<div class="callout"><div style="font-size:12px;opacity:.85;">${escapeHtml(title)}</div><div class="price">${formatCurrencyPreview(total, currency)}</div></div>`;
    case 'quoteMeta': {
      const fullName = [live?.customer_first_name, live?.customer_last_name].filter(Boolean).join(' ').trim();
      const name = fullName || 'Jane Smith';
      const email = live?.customer_email || 'jane@example.com';
      const ref = live?.quote_reference || 'SQ-2026-00123';
      const date = live?.created_at
        ? new Date(live.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
        : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      const custRef = live?.customer_reference || cfgData?.customerReference;
      const quoteName = live?.quote_name || cfgData?.quoteName;
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">Customer Name</span><span class="val">${escapeHtml(name)}</span></div>
        <div class="row"><span class="muted">Email</span><span class="val">${escapeHtml(email)}</span></div>
        <div class="row"><span class="muted">Quote Reference</span><span class="val">${escapeHtml(ref)}</span></div>
        ${quoteName ? `<div class="row"><span class="muted">Quote Name</span><span class="val">${escapeHtml(quoteName)}</span></div>` : ''}
        ${custRef ? `<div class="row"><span class="muted">Customer Reference</span><span class="val">${escapeHtml(custRef)}</span></div>` : ''}
        <div class="row"><span class="muted">Date</span><span class="val">${escapeHtml(date)}</span></div>`;
    }
    case 'stepSelections': {
      const manufacturing = cfgData?.measurementOption === 'exact'
        ? 'Manufacture Shade Sail to the Exact Dimensions I provide'
        : 'Manufacture Shade Sail to fit my Space';
      const hwMode = cfgData?.hardwareSelectionMode || (cfgData?.measurementOption === 'adjust' ? 'standard' : 'none');
      const hwLabel = hwMode === 'standard' ? `Standard tensioning kit included (${corners}-corner pack)` : hwMode === 'manual' ? 'Manual hardware per corner' : 'No tensioning hardware';
      const fixingLabel = cfgData?.fixingPointsInstalled === true ? 'Already installed' : cfgData?.fixingPointsInstalled === false ? 'Planning installation' : 'Not specified';
      const edgeLabel = cfgData?.edgeType === 'webbing' ? 'Webbing reinforced' : cfgData?.edgeType === 'cabled' ? 'Cabled edge' : 'Webbing reinforced';
      const rows: Array<[string, string]> = [
        ['Manufacturing Approach', manufacturing],
        ['Number of Corners', `${corners}-corner shade sail`],
        ['Measurement Units', unit === 'metric' ? 'Metric (mm / m)' : 'Imperial (in / ft)'],
        ['Fabric', `${fabricLabel}${fabricColor ? ` - ${fabricColor}` : ''}`],
        ['Edge Reinforcement', edgeLabel],
        ['Tensioning Hardware', hwLabel],
        ['Fixing Points', fixingLabel],
      ];
      return `<h2>${escapeHtml(title)}</h2>${rows.map(([label, value], idx) => `<div class="row"><span class="muted">Step ${idx + 1} - ${escapeHtml(label)}</span><span class="val">${escapeHtml(value)}</span></div>`).join('')}`;
    }
    case 'diagramImage': {
      const mw = Number(p.maxWidth) || 520;
      if (live?.diagram_public_url) {
        return `<h2>${escapeHtml(title)}</h2>
          <div style="text-align:center;"><img src="${escapeHtml(live.diagram_public_url)}" alt="Shade sail diagram" style="max-width:${mw}px;width:100%;border:1px solid #E2E8F0;border-radius:8px;padding:10px;background:#fff;" /></div>`;
      }
      return `<h2>${escapeHtml(title)}</h2>
        <div style="text-align:center;padding:16px;border:1px dashed ${cfg.brand.mutedColor};border-radius:8px;color:${cfg.brand.mutedColor};font-size:12px;max-width:${mw}px;margin:0 auto;">Shade sail diagram appears here. The PDF will use the live diagram captured when the quote was created.</div>`;
    }
    case 'billOfMaterials':
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">${escapeHtml(fabricLabel)} - ${escapeHtml(fabricColor)} (${formatAreaPreview((calc?.area || 12.5) * 1000000, unit)})</span><span class="val">${formatCurrencyPreview(total - 70, currency)}</span></div>
        <div class="row"><span class="muted">Edge reinforcement</span><span class="val">Included</span></div>
        <div class="row"><span class="muted">Hardware Tensioning Kit (${corners}-corner pack)</span><span class="val">Included</span></div>
        <div class="row"><span class="val">Total (all-inclusive)</span><span class="val">${formatCurrencyPreview(total, currency)}</span></div>`;
    case 'resumeButton': {
      const label = (p.label as string) || 'Open My Saved Quote';
      const url = live ? `https://shadespace.com/pages/shade-sail-configurator?quote=${live.id}&token=${encodeURIComponent(live.access_token)}` : null;
      return `<div style="margin:16px 0;text-align:center;padding:20px;border-radius:10px;background:${cfg.brand.primaryColor};color:#fff;">
        <div style="font-weight:700;margin-bottom:6px;">${escapeHtml(title)}</div>
        <div style="font-size:12px;opacity:.85;margin-bottom:12px;">Pick up exactly where you left off and add this configuration to your cart.</div>
        <span style="display:inline-block;background:${cfg.brand.accentColor};color:${cfg.brand.primaryColor};padding:10px 24px;border-radius:6px;font-weight:700;font-size:13px;">${escapeHtml(label)}</span>
        ${url ? `<div style="font-size:10px;margin-top:10px;opacity:0.7;word-break:break-all;">${escapeHtml(url)}</div>` : ''}
      </div>`;
    }
    case 'customText': {
      const align = (p.align as string) || 'left';
      const heading = p.heading ? `<div style="font-weight:700;margin-bottom:6px;color:${cfg.brand.primaryColor};">${escapeHtml(p.heading)}</div>` : '';
      return `<div style="margin:12px 0;text-align:${align};font-size:13px;">${heading}<div>${escapeHtml(p.body || '')}</div></div>`;
    }
    case 'customImage':
      return p.url ? `<div style="margin:12px 0;text-align:center;"><img src="${escapeHtml(p.url)}" alt="${escapeHtml(p.alt || '')}" style="max-width:${Number(p.width) || 400}px;width:100%;" /></div>` : '';
    case 'customHtml':
      return `<div style="margin:12px 0;font-size:13px;">${sanitizeCustomHtml(String(p.html || ''))}</div>`;
    case 'divider':
      return `<hr style="border-top:${Number(p.thickness) || 1}px solid ${cfg.brand.mutedColor};opacity:0.4;" />`;
    case 'spacer':
      return `<div style="height:${Number(p.height) || 16}px;"></div>`;
    case 'pageBreak':
      return `<div style="margin:16px 0;border-top:1px dashed ${cfg.brand.mutedColor};position:relative;height:18px;">
        <span style="position:absolute;top:-9px;left:50%;transform:translateX(-50%);background:${cfg.brand.backgroundColor};padding:0 8px;font-size:10px;letter-spacing:0.1em;text-transform:uppercase;color:${cfg.brand.mutedColor};">Page Break</span>
      </div>`;
    default:
      return '';
  }
}
