import React, { useEffect, useMemo, useState } from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { supabase } from '../../lib/supabase';

export interface PdfTemplateConfig {
  brand: {
    primaryColor: string;
    accentColor: string;
    accentDark: string;
    textColor: string;
    mutedColor: string;
    backgroundColor: string;
    logoUrl: string;
    fontFamily: string;
  };
  header: {
    title: string;
    tagline: string;
  };
  footer: {
    line1: string;
    line2: string;
  };
  sections: {
    showSummary: boolean;
    showMeasurements: boolean;
    showAnchorPoints: boolean;
    showHardwareBreakdown: boolean;
    showPriceBreakdown: boolean;
    showGuarantee: boolean;
    showPricingCallout: boolean;
  };
  paper: 'A4' | 'Letter';
}

interface PdfTemplateRow {
  id: string;
  name: string;
  is_active: boolean;
  config: PdfTemplateConfig;
  updated_at: string;
}

const DEFAULT_CONFIG: PdfTemplateConfig = {
  brand: {
    primaryColor: '#01312D',
    accentColor: '#BFF102',
    accentDark: '#307C31',
    textColor: '#01312D',
    mutedColor: '#64748B',
    backgroundColor: '#FFFFFF',
    logoUrl: '',
    fontFamily: 'Helvetica, Arial, sans-serif',
  },
  header: { title: 'Custom Shade Sail Quote', tagline: 'Where Cool Spaces Begin' },
  footer: {
    line1: 'Generated by ShadeSpace Professional Configurator',
    line2: 'Visit shadespace.com for more information',
  },
  sections: {
    showSummary: true,
    showMeasurements: true,
    showAnchorPoints: true,
    showHardwareBreakdown: true,
    showPriceBreakdown: true,
    showGuarantee: true,
    showPricingCallout: true,
  },
  paper: 'A4',
};

function mergeConfig(input: Partial<PdfTemplateConfig> | null | undefined): PdfTemplateConfig {
  return {
    brand: { ...DEFAULT_CONFIG.brand, ...(input?.brand || {}) },
    header: { ...DEFAULT_CONFIG.header, ...(input?.header || {}) },
    footer: { ...DEFAULT_CONFIG.footer, ...(input?.footer || {}) },
    sections: { ...DEFAULT_CONFIG.sections, ...(input?.sections || {}) },
    paper: (input?.paper as 'A4' | 'Letter') || DEFAULT_CONFIG.paper,
  };
}

export const PdfStudio: React.FC = () => {
  const [templates, setTemplates] = useState<PdfTemplateRow[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [config, setConfig] = useState<PdfTemplateConfig>(DEFAULT_CONFIG);
  const [name, setName] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ kind: 'ok' | 'err'; text: string } | null>(null);

  const loadTemplates = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('pdf_templates')
      .select('*')
      .order('created_at', { ascending: true });
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      setLoading(false);
      return;
    }
    const rows = (data || []) as PdfTemplateRow[];
    setTemplates(rows);
    const active = rows.find((r) => r.is_active) || rows[0];
    if (active) {
      setActiveId(active.id);
      setName(active.name);
      setConfig(mergeConfig(active.config));
    }
    setLoading(false);
  };

  useEffect(() => {
    loadTemplates();
  }, []);

  const handleSelect = (id: string) => {
    const row = templates.find((t) => t.id === id);
    if (!row) return;
    setActiveId(id);
    setName(row.name);
    setConfig(mergeConfig(row.config));
    setMessage(null);
  };

  const handleSave = async () => {
    if (!activeId) return;
    setSaving(true);
    setMessage(null);
    const { error } = await supabase
      .from('pdf_templates')
      .update({ name, config, updated_at: new Date().toISOString() })
      .eq('id', activeId);
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template saved.' });
    loadTemplates();
  };

  const handleSetActive = async () => {
    if (!activeId) return;
    setSaving(true);
    await supabase.from('pdf_templates').update({ is_active: false }).neq('id', activeId);
    const { error } = await supabase
      .from('pdf_templates')
      .update({ is_active: true })
      .eq('id', activeId);
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template activated.' });
    loadTemplates();
  };

  const handleDuplicate = async () => {
    const newName = `${name} (copy)`;
    setSaving(true);
    const { data, error } = await supabase
      .from('pdf_templates')
      .insert({ name: newName, is_active: false, config })
      .select()
      .single();
    setSaving(false);
    if (error) {
      setMessage({ kind: 'err', text: error.message });
      return;
    }
    setMessage({ kind: 'ok', text: 'Template duplicated.' });
    await loadTemplates();
    if (data) setActiveId((data as PdfTemplateRow).id);
  };

  const handleReset = () => {
    setConfig(DEFAULT_CONFIG);
  };

  const previewHtml = useMemo(() => buildPreview(config), [config]);

  if (loading) {
    return <Card className="p-6">Loading templates...</Card>;
  }

  return (
    <div className="space-y-6">
      <Card className="p-4 sm:p-6 border border-gray-200">
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-xs font-medium text-gray-600 mb-1">Template</label>
            <select
              value={activeId || ''}
              onChange={(e) => handleSelect(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-lime-500 focus:border-lime-500"
            >
              {templates.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name} {t.is_active ? '(active)' : ''}
                </option>
              ))}
            </select>
          </div>
          <div className="flex-1 min-w-[200px]">
            <label className="block text-xs font-medium text-gray-600 mb-1">Name</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-lime-500 focus:border-lime-500"
            />
          </div>
          <div className="flex gap-2 pt-5">
            <Button onClick={handleSave} disabled={saving}>Save</Button>
            <Button onClick={handleSetActive} disabled={saving} variant="outline">Set Active</Button>
            <Button onClick={handleDuplicate} disabled={saving} variant="outline">Duplicate</Button>
            <Button onClick={handleReset} disabled={saving} variant="outline">Reset to defaults</Button>
          </div>
        </div>
        {message && (
          <div
            className={`mt-3 text-sm px-3 py-2 rounded ${
              message.kind === 'ok'
                ? 'bg-lime-50 text-lime-800 border border-lime-200'
                : 'bg-red-50 text-red-800 border border-red-200'
            }`}
          >
            {message.text}
          </div>
        )}
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-4 sm:p-6 border border-gray-200 space-y-6">
          <Section title="Branding">
            <ColorRow
              label="Primary"
              value={config.brand.primaryColor}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, primaryColor: v } })}
            />
            <ColorRow
              label="Accent"
              value={config.brand.accentColor}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, accentColor: v } })}
            />
            <ColorRow
              label="Accent Dark"
              value={config.brand.accentDark}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, accentDark: v } })}
            />
            <ColorRow
              label="Text"
              value={config.brand.textColor}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, textColor: v } })}
            />
            <ColorRow
              label="Muted"
              value={config.brand.mutedColor}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, mutedColor: v } })}
            />
            <ColorRow
              label="Background"
              value={config.brand.backgroundColor}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, backgroundColor: v } })}
            />
            <TextRow
              label="Logo URL"
              value={config.brand.logoUrl}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, logoUrl: v } })}
              placeholder="https://..."
            />
            <TextRow
              label="Font family"
              value={config.brand.fontFamily}
              onChange={(v) => setConfig({ ...config, brand: { ...config.brand, fontFamily: v } })}
              placeholder="Helvetica, Arial, sans-serif"
            />
          </Section>

          <Section title="Header">
            <TextRow
              label="Title"
              value={config.header.title}
              onChange={(v) => setConfig({ ...config, header: { ...config.header, title: v } })}
            />
            <TextRow
              label="Tagline"
              value={config.header.tagline}
              onChange={(v) => setConfig({ ...config, header: { ...config.header, tagline: v } })}
            />
          </Section>

          <Section title="Footer">
            <TextRow
              label="Line 1"
              value={config.footer.line1}
              onChange={(v) => setConfig({ ...config, footer: { ...config.footer, line1: v } })}
            />
            <TextRow
              label="Line 2"
              value={config.footer.line2}
              onChange={(v) => setConfig({ ...config, footer: { ...config.footer, line2: v } })}
            />
          </Section>

          <Section title="Sections">
            {(Object.keys(config.sections) as Array<keyof typeof config.sections>).map((key) => (
              <label key={key} className="flex items-center gap-2 text-sm text-gray-700">
                <input
                  type="checkbox"
                  checked={config.sections[key]}
                  onChange={(e) =>
                    setConfig({
                      ...config,
                      sections: { ...config.sections, [key]: e.target.checked },
                    })
                  }
                  className="rounded border-gray-300 text-lime-600 focus:ring-lime-500"
                />
                {prettyKey(key)}
              </label>
            ))}
          </Section>

          <Section title="Paper">
            <div className="flex gap-2">
              {(['A4', 'Letter'] as const).map((p) => (
                <button
                  key={p}
                  type="button"
                  onClick={() => setConfig({ ...config, paper: p })}
                  className={`px-3 py-1.5 rounded-lg border text-sm ${
                    config.paper === p
                      ? 'border-lime-500 bg-lime-50 text-lime-800'
                      : 'border-gray-300 text-gray-600 hover:bg-gray-50'
                  }`}
                >
                  {p}
                </button>
              ))}
            </div>
          </Section>
        </Card>

        <Card className="p-0 border border-gray-200 overflow-hidden">
          <div className="px-4 py-3 border-b border-gray-200 bg-gray-50 text-sm font-semibold text-gray-700">
            Live preview
          </div>
          <iframe
            title="pdf-preview"
            srcDoc={previewHtml}
            className="w-full bg-white"
            style={{ height: '720px', border: 'none' }}
          />
        </Card>
      </div>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div>
    <h3 className="text-sm font-semibold text-gray-800 mb-2">{title}</h3>
    <div className="space-y-2">{children}</div>
  </div>
);

const ColorRow: React.FC<{ label: string; value: string; onChange: (v: string) => void }> = ({
  label,
  value,
  onChange,
}) => (
  <div className="flex items-center gap-3">
    <label className="w-28 text-xs text-gray-600">{label}</label>
    <input
      type="color"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="h-8 w-10 border border-gray-300 rounded"
    />
    <input
      type="text"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className="flex-1 border border-gray-300 rounded px-2 py-1.5 text-sm font-mono"
    />
  </div>
);

const TextRow: React.FC<{
  label: string;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
}> = ({ label, value, onChange, placeholder }) => (
  <div className="flex items-center gap-3">
    <label className="w-28 text-xs text-gray-600">{label}</label>
    <input
      type="text"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      className="flex-1 border border-gray-300 rounded px-2 py-1.5 text-sm"
    />
  </div>
);

function prettyKey(key: string): string {
  return key
    .replace(/^show/, '')
    .replace(/([A-Z])/g, ' $1')
    .trim();
}

function buildPreview(cfg: PdfTemplateConfig): string {
  const b = cfg.brand;
  const s = cfg.sections;
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
    body { margin:0; padding:24px; background:${b.backgroundColor}; font-family:${b.fontFamily}; color:${b.textColor}; }
    .header { display:flex; align-items:center; gap:12px; padding:16px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${b.accentColor} 100%); border:2px solid ${b.accentDark}; margin-bottom:16px; }
    .logo { width:48px; height:48px; object-fit:contain; background:#fff; border-radius:8px; padding:4px; }
    .title { font-size:22px; font-weight:700; color:${b.primaryColor}; margin:0; }
    .tagline { font-size:12px; color:${b.accentDark}; margin:4px 0 0 0; }
    h2 { font-size:16px; color:${b.primaryColor}; border-bottom:2px solid ${b.accentColor}; padding-bottom:6px; margin:20px 0 10px; }
    .row { display:flex; justify-content:space-between; padding:6px 0; border-bottom:1px solid #E5E7EB; font-size:13px; }
    .muted { color:${b.mutedColor}; }
    .val { color:${b.textColor}; font-weight:600; }
    .callout { margin-top:16px; padding:16px; border-radius:12px; background:${b.primaryColor}; color:#fff; text-align:center; }
    .callout .price { font-size:22px; font-weight:700; color:${b.accentColor}; }
    .footer { margin-top:24px; text-align:center; font-size:11px; color:${b.mutedColor}; }
  </style></head><body>
    <div class="header">
      ${b.logoUrl ? `<img class="logo" src="${escapeHtml(b.logoUrl)}" alt="logo" />` : ''}
      <div>
        <h1 class="title">${escapeHtml(cfg.header.title)}</h1>
        <p class="tagline">${escapeHtml(cfg.header.tagline)}</p>
      </div>
    </div>
    ${s.showSummary ? `<h2>Shade Sail Summary</h2>
      <div class="row"><span class="muted">Fabric Material</span><span class="val">Monotec 370</span></div>
      <div class="row"><span class="muted">Fabric Color</span><span class="val">Domino Black</span></div>
      <div class="row"><span class="muted">Shade Factor</span><span class="val">88.4%</span></div>
      <div class="row"><span class="muted">Warranty</span><span class="val">15 Years</span></div>
      <div class="row"><span class="muted">Corners</span><span class="val">4</span></div>` : ''}
    ${s.showMeasurements ? `<h2>Precise Measurements</h2>
      <div class="row"><span class="muted">Edge A to B</span><span class="val">4000mm</span></div>
      <div class="row"><span class="muted">Edge B to C</span><span class="val">3500mm</span></div>` : ''}
    ${s.showAnchorPoints ? `<h2>Anchor Point Configuration</h2>
      <div class="row"><span class="muted">Corner A</span><span class="val">2400mm, post</span></div>` : ''}
    ${s.showHardwareBreakdown ? `<h2>Corner Hardware Breakdown</h2>
      <div class="row"><span class="muted">1x Turnbuckle</span><span class="val">NZ$25.00</span></div>` : ''}
    ${s.showPriceBreakdown ? `<h2>Price Breakdown</h2>
      <div class="row"><span class="muted">Shade sail</span><span class="val">NZ$580.00</span></div>
      <div class="row"><span class="val">Total</span><span class="val">NZ$650.00</span></div>` : ''}
    ${s.showGuarantee ? `<h2>Premium Quality Guarantee</h2>
      <div class="muted" style="font-size:12px;">15-year Fabric &amp; Workmanship Warranty · Weather-resistant materials · Free worldwide shipping</div>` : ''}
    ${s.showPricingCallout ? `<div class="callout">
      <div class="muted" style="color:#fff; font-size:12px;">All-Inclusive Price to Your Door</div>
      <div class="price">NZ$650.00</div>
    </div>` : ''}
    <div class="footer">
      <div>${escapeHtml(cfg.footer.line1)}</div>
      <div>${escapeHtml(cfg.footer.line2)}</div>
    </div>
  </body></html>`;
}

function escapeHtml(s: string): string {
  return String(s || '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c] as string));
}
