import { supabase } from '../lib/supabase';
import { DEFAULT_BLOCKS, DEFAULT_FULFILMENT_BLOCKS, PdfBlock, BlockType, newBlockId } from './pdfBlocks';

export type PdfTemplateType = 'quote' | 'fulfilment';

export interface ActivePdfTemplate {
  blocks: PdfBlock[];
  chrome: {
    brand?: {
      primaryColor?: string;
      accentColor?: string;
      accentDark?: string;
      textColor?: string;
      mutedColor?: string;
      backgroundColor?: string;
      logoUrl?: string;
    };
    header?: { title?: string; tagline?: string };
    footer?: { line1?: string; line2?: string };
    paper?: 'A4' | 'Letter';
  };
  layout: {
    density: 'comfortable' | 'compact' | 'ultra';
    columns: 1 | 2;
    columnGap?: number;
  };
}

const DEFAULT_TEMPLATE: ActivePdfTemplate = {
  blocks: DEFAULT_BLOCKS.map((b) => ({ ...b, id: newBlockId() })),
  chrome: {
    brand: {
      primaryColor: '#01312D',
      accentColor: '#BFF102',
      accentDark: '#307C31',
      textColor: '#01312D',
      mutedColor: '#64748B',
      backgroundColor: '#FFFFFF',
    },
    header: { title: 'Custom Shade Sail Quote', tagline: 'Where Cool Spaces Begin' },
    footer: {
      line1: 'Generated by ShadeSpace Professional Configurator',
      line2: 'Visit shadespace.com for more information',
    },
    paper: 'A4',
  },
  layout: { density: 'comfortable', columns: 1 },
};

const DEFAULT_FULFILMENT_TEMPLATE: ActivePdfTemplate = {
  blocks: DEFAULT_FULFILMENT_BLOCKS.map((b) => ({ ...b, id: newBlockId() })),
  chrome: {
    brand: {
      primaryColor: '#1E293B',
      accentColor: '#BFF102',
      accentDark: '#307C31',
      textColor: '#1E293B',
      mutedColor: '#64748B',
      backgroundColor: '#FFFFFF',
    },
    header: { title: 'FULFILLMENT ORDER', tagline: 'Internal Staff Document' },
    footer: {
      line1: 'ShadeSpace Fulfilment - Internal Use Only',
      line2: 'Do not share with customers',
    },
    paper: 'A4',
  },
  layout: { density: 'compact', columns: 1 },
};

function normalizeBlocks(input: unknown, fallback: PdfBlock[]): PdfBlock[] {
  if (!Array.isArray(input) || input.length === 0) return fallback;
  return input
    .filter((b) => b && typeof b === 'object')
    .map((raw) => {
      const b = raw as Partial<PdfBlock>;
      return {
        id: typeof b.id === 'string' && b.id ? b.id : newBlockId(),
        type: (b.type as BlockType) || 'customText',
        visible: b.visible !== false,
        props: (b.props && typeof b.props === 'object' ? b.props : {}) as Record<string, unknown>,
      };
    });
}

const cacheMap: Record<PdfTemplateType, { value: ActivePdfTemplate; ts: number } | null> = {
  quote: null,
  fulfilment: null,
};
const CACHE_MS = 60_000;

export async function loadActivePdfTemplate(force = false, type: PdfTemplateType = 'quote'): Promise<ActivePdfTemplate> {
  const cached = cacheMap[type];
  if (!force && cached && Date.now() - cached.ts < CACHE_MS) return cached.value;
  const fallbackTemplate = type === 'fulfilment' ? DEFAULT_FULFILMENT_TEMPLATE : DEFAULT_TEMPLATE;
  try {
    const { data } = await supabase
      .from('pdf_templates')
      .select('config, blocks')
      .eq('is_active', true)
      .eq('template_type', type)
      .maybeSingle();
    if (!data) {
      cacheMap[type] = { value: fallbackTemplate, ts: Date.now() };
      return fallbackTemplate;
    }
    const cfg = (data.config || {}) as Record<string, unknown>;
    const brand = (cfg.brand as ActivePdfTemplate['chrome']['brand']) || {};
    const header = (cfg.header as ActivePdfTemplate['chrome']['header']) || {};
    const footer = (cfg.footer as ActivePdfTemplate['chrome']['footer']) || {};
    const layout = (cfg.layout as Partial<ActivePdfTemplate['layout']>) || {};
    const value: ActivePdfTemplate = {
      blocks: normalizeBlocks(data.blocks, fallbackTemplate.blocks),
      chrome: {
        brand: { ...fallbackTemplate.chrome.brand, ...brand },
        header: { ...fallbackTemplate.chrome.header, ...header },
        footer: { ...fallbackTemplate.chrome.footer, ...footer },
        paper: (cfg.paper as 'A4' | 'Letter') || fallbackTemplate.chrome.paper,
      },
      layout: {
        density: (layout.density as ActivePdfTemplate['layout']['density']) || fallbackTemplate.layout.density,
        columns: (layout.columns === 2 ? 2 : 1) as 1 | 2,
        columnGap: typeof layout.columnGap === 'number' ? layout.columnGap : undefined,
      },
    };
    cacheMap[type] = { value, ts: Date.now() };
    return value;
  } catch (err) {
    console.warn('[loadActivePdfTemplate] Failed, using defaults:', err);
    return fallbackTemplate;
  }
}
