import { ConfiguratorState, ShadeCalculations } from '../types';
import { captureSvgToBase64Png } from './svgCapture';
import { renderSailSvgOffscreen } from './renderSvgOffscreen';
import { PdfBlock } from './pdfBlocks';
import {
  buildQuotePreviewHtml,
  PdfTemplateConfig,
  PreviewLiveData,
} from './pdfHtmlPreview';
import { renderQuotePdfFromHtml } from './pdfHtmlRenderer';

interface PdfTemplateBranding {
  primaryColor?: string;
  accentColor?: string;
  accentDark?: string;
  textColor?: string;
  mutedColor?: string;
  backgroundColor?: string;
  logoUrl?: string;
  fontFamily?: string;
}

interface PdfTemplateChrome {
  brand?: PdfTemplateBranding;
  header?: { title?: string; tagline?: string };
  footer?: { line1?: string; line2?: string };
  paper?: 'A4' | 'Letter';
}

export interface CustomerDetails {
  firstName?: string;
  lastName?: string;
  email?: string;
  quoteName?: string;
  customerReference?: string | null;
  quoteUrl?: string;
}

export type PdfDensity = 'comfortable' | 'compact' | 'ultra';

interface PdfLayoutOptions {
  density?: PdfDensity;
  columns?: 1 | 2;
  columnGap?: number;
  baseFontPt?: number;
  rowGapMm?: number;
  sectionGapMm?: number;
  returnBlob?: boolean;
}

export interface BlockPdfOptions {
  layout?: PdfLayoutOptions;
  chrome?: PdfTemplateChrome;
  customer?: CustomerDetails;
  svgElement?: SVGElement;
  threeDImageDataUrl?: string;
  returnBlob?: boolean;
  isEmailSummary?: boolean;
}

const DEFAULT_LOGO_URL = 'https://cdn.shopify.com/s/files/1/0778/8730/7969/files/Logo-horizontal-color_3x_8d83ab71-75cc-4486-8cf3-b510cdb69aa7.png?v=1728339550';

function buildTemplateConfig(chrome: PdfTemplateChrome, layout: PdfLayoutOptions | undefined): PdfTemplateConfig {
  const brand = chrome.brand || {};
  return {
    brand: {
      primaryColor: brand.primaryColor || '#01312D',
      accentColor: brand.accentColor || '#BFF102',
      accentDark: brand.accentDark || '#307C31',
      textColor: brand.textColor || '#01312D',
      mutedColor: brand.mutedColor || '#64748B',
      backgroundColor: brand.backgroundColor || '#FFFFFF',
      logoUrl: brand.logoUrl || DEFAULT_LOGO_URL,
      fontFamily: brand.fontFamily || 'Helvetica, Arial, sans-serif',
    },
    header: {
      title: chrome.header?.title || 'Custom Shade Sail Quote',
      tagline: chrome.header?.tagline || 'Where Cool Spaces Begin',
    },
    footer: {
      line1: chrome.footer?.line1 || 'Generated by ShadeSpace Professional Configurator',
      line2: chrome.footer?.line2 || 'Visit shadespace.com for more information',
    },
    sections: {
      showSummary: true,
      showMeasurements: true,
      showAnchorPoints: true,
      showHardwareBreakdown: true,
      showPriceBreakdown: true,
      showGuarantee: true,
      showPricingCallout: true,
    },
    paper: chrome.paper === 'Letter' ? 'Letter' : 'A4',
    layout: {
      density: layout?.density || 'comfortable',
      columns: layout?.columns === 2 ? 2 : 1,
      columnGap: layout?.columnGap,
    },
  };
}

function buildLiveData(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  customer: CustomerDetails | undefined,
  diagramDataUrl: string | undefined,
  threeDImageDataUrl?: string,
): PreviewLiveData {
  const fullName = [customer?.firstName, customer?.lastName].filter(Boolean).join(' ').trim();
  return {
    id: undefined,
    quote_reference: null,
    quote_name: customer?.quoteName || null,
    customer_first_name: customer?.firstName || null,
    customer_last_name: customer?.lastName || null,
    customer_email: customer?.email || null,
    customer_reference: customer?.customerReference || null,
    access_token: null,
    diagram_public_url: diagramDataUrl || null,
    diagram_3d_url: threeDImageDataUrl || null,
    created_at: new Date().toISOString(),
    config_data: config,
    calculations_data: calculations,
    // unused but lets the resume button know we have a quote URL
    ...(customer?.quoteUrl ? { resumeUrl: customer.quoteUrl } : {}),
    ...(fullName ? {} : {}),
  } as PreviewLiveData;
}

/**
 * Generate a customer-facing PDF that visually matches the PDF Studio HTML preview.
 * The renderer captures the same HTML used in the studio iframe and slices it into
 * paginated PDF pages — this guarantees preview ≡ PDF.
 */
export async function generatePdfFromBlocks(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  blocks: PdfBlock[],
  options: BlockPdfOptions = {},
): Promise<string | void> {
  const cfg = buildTemplateConfig(options.chrome || {}, options.layout);

  let diagramDataUrl: string | undefined;
  if (options.svgElement) {
    try {
      diagramDataUrl = await captureSvgToBase64Png(options.svgElement as SVGSVGElement, 800, 800);
    } catch {
      // ignore
    }
  }
  if (!diagramDataUrl && config.points && config.points.length >= 3) {
    try {
      diagramDataUrl = await renderSailSvgOffscreen(config, 800, 800);
    } catch {
      // ignore
    }
  }

  const live = buildLiveData(config, calculations, options.customer, diagramDataUrl, options.threeDImageDataUrl);
  const html = buildQuotePreviewHtml(cfg, blocks, live, { pageMode: true });

  return renderQuotePdfFromHtml(html, {
    paper: cfg.paper,
    returnBlobUrl: options.returnBlob === true,
    returnDataUri: options.isEmailSummary === true && options.returnBlob !== true,
    filename: `ShadeSpace-Quote-${new Date().toISOString().slice(0, 10)}.pdf`,
  });
}
