import { ConfiguratorState, ShadeCalculations } from '../types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export interface SavedQuote {
  id: string;
  reference: string;
  expiresAt: string;
  pricingLockedUntil: string;
  quoteName: string;
  customerReference?: string | null;
  nameAutoGenerated: boolean;
  accessToken: string;
  shopifyCustomerCreated?: boolean;
  shopifyCustomerId?: string | null;
  currentStep?: number;
  totalSteps?: number;
  status?: string;
}

export interface QuoteData {
  id: string;
  quote_reference: string;
  quote_name: string;
  customer_reference?: string | null;
  name_auto_generated: boolean;
  customer_email?: string;
  config_data: ConfiguratorState;
  calculations_data: ShadeCalculations;
  pricing_snapshot?: Record<string, unknown> | null;
  created_at: string;
  expires_at: string;
  pricing_locked_until: string;
  pricing_status: 'locked' | 'live';
  status: string;
  current_step?: number;
  total_steps?: number;
}


/**
 * Save a quote to the database
 */
export async function saveQuote(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  email?: string,
  quoteName?: string,
  customerReference?: string,
  currentStep?: number,
  totalSteps?: number,
  pricingSnapshot?: Record<string, unknown> | null,
  firstName?: string,
  lastName?: string
): Promise<SavedQuote> {
  const response = await fetch(`${SUPABASE_URL}/functions/v1/save-quote`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      config,
      calculations,
      email: email || null,
      quoteName: quoteName || null,
      customerReference: customerReference || null,
      currentStep: currentStep ?? null,
      totalSteps: totalSteps ?? 7,
      pricingSnapshot: pricingSnapshot ?? null,
      firstName: firstName || null,
      lastName: lastName || null,
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to save quote');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    pricingLockedUntil: data.quote.pricingLockedUntil,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
    currentStep: data.quote.currentStep,
    totalSteps: data.quote.totalSteps,
    status: data.quote.status,
  };
}

/**
 * Retrieve a quote by ID and access token
 */
export async function getQuoteById(id: string, accessToken: string): Promise<QuoteData> {
  const response = await fetch(
    `${SUPABASE_URL}/functions/v1/save-quote?id=${encodeURIComponent(id)}&token=${encodeURIComponent(accessToken)}`,
    {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
        'Content-Type': 'application/json',
      },
    }
  );

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to retrieve quote');
  }

  return data.quote;
}

/**
 * Update quote status (e.g., mark as completed)
 */
export async function updateQuoteStatus(
  id: string,
  accessToken: string,
  status: 'saved' | 'completed' | 'expired'
): Promise<void> {
  const response = await fetch(`${SUPABASE_URL}/functions/v1/save-quote`, {
    method: 'PATCH',
    headers: {
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ id, token: accessToken, status }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to update quote status');
  }
}

/**
 * Generate a shareable quote URL with access token
 * Uses the current window origin - only use for in-app display (e.g. "copy link" buttons)
 */
export function generateQuoteUrl(quoteId: string, accessToken: string): string {
  const baseUrl = window.location.origin;
  return `${baseUrl}${window.location.pathname}?quote=${quoteId}&token=${encodeURIComponent(accessToken)}`;
}

/**
 * Generate a canonical, domain-neutral quote URL that routes through a Supabase
 * Edge Function and then redirects to the canonical shadespace.com configurator URL.
 * Shopify's own market-based redirect then forwards the visitor to their regional
 * domain (.com.au, .co.uk, .ca, etc.) while preserving the quote/token params.
 *
 * Use this for every external artifact (emails, PDFs, admin share links) so the
 * link keeps working no matter which regional domain the customer lands on.
 */
export function generateCanonicalQuoteUrl(
  quoteId: string,
  accessToken: string,
  source: 'email' | 'pdf' | 'admin' | 'share' = 'share'
): string {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const params = new URLSearchParams({
    id: quoteId,
    token: accessToken,
    src: source,
  });
  if (!supabaseUrl) {
    return generateQuoteUrl(quoteId, accessToken);
  }
  return `${supabaseUrl}/functions/v1/quote-redirect?${params.toString()}`;
}

const ACTIVE_QUOTE_STORAGE_KEY = 'shadespace_active_quote';

function readQuoteFromStorage(): { id: string; token: string } | null {
  try {
    const raw = sessionStorage.getItem(ACTIVE_QUOTE_STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { id?: string; token?: string };
    if (parsed && parsed.id && parsed.token) {
      return { id: parsed.id, token: parsed.token };
    }
  } catch {
    // ignore malformed storage
  }
  return null;
}

function writeQuoteToStorage(quote: { id: string; token: string }): void {
  try {
    sessionStorage.setItem(ACTIVE_QUOTE_STORAGE_KEY, JSON.stringify(quote));
  } catch {
    // ignore quota / access errors
  }
}

export function clearActiveQuote(): void {
  try {
    sessionStorage.removeItem(ACTIVE_QUOTE_STORAGE_KEY);
  } catch {
    // ignore
  }
}

export function hasActiveQuoteContext(): boolean {
  const urlParams = new URLSearchParams(window.location.search);
  if (urlParams.get('quote') && urlParams.get('token')) return true;
  return readQuoteFromStorage() !== null;
}

/**
 * Get quote ID and token from URL if present.
 * Falls back to sessionStorage if a Shopify regional redirect stripped the params
 * so the customer can still resume a saved quote after the domain switch.
 */
export function getQuoteFromUrl(): { id: string; token: string } | null {
  const urlParams = new URLSearchParams(window.location.search);
  const id = urlParams.get('quote');
  const token = urlParams.get('token');

  if (id && token) {
    const result = { id, token };
    writeQuoteToStorage(result);
    return result;
  }

  return readQuoteFromStorage();
}

export function formatExpirationDate(expiresAt: string): string {
  const date = new Date(expiresAt);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function formatPricingLockDate(pricingLockedUntil: string): string {
  const date = new Date(pricingLockedUntil);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function isPricingLocked(pricingLockedUntil: string): boolean {
  return new Date(pricingLockedUntil) > new Date();
}

/**
 * Mark quote as converted to cart
 */
export async function markQuoteConverted(quoteId: string, accessToken: string): Promise<void> {
  await updateQuoteStatus(quoteId, accessToken, 'completed');
}

