import { ConfiguratorState, ShadeCalculations } from '../types';
import { getAdminAuthHeaders } from './adminAuth';
import { getIpDetectionCache } from './currencySync';

// Route save-quote calls through the Shopify App Proxy so the browser never
// makes direct Supabase DNS requests (avoids ERR_NAME_NOT_RESOLVED / CORS).
const SAVE_QUOTE_URL = '/apps/shade_space/save-quote';

export interface SavedQuote {
  id: string;
  reference: string;
  expiresAt: string;
  pricingLockedUntil: string;
  quoteName: string;
  customerReference?: string | null;
  nameAutoGenerated: boolean;
  accessToken: string;
  shopifyCustomerCreated?: boolean;
  shopifyCustomerId?: string | null;
  currentStep?: number;
  totalSteps?: number;
  status?: string;
}

export interface QuoteData {
  id: string;
  quote_reference: string;
  quote_name: string;
  customer_reference?: string | null;
  name_auto_generated: boolean;
  customer_email?: string;
  config_data: ConfiguratorState;
  calculations_data: ShadeCalculations;
  pricing_snapshot?: Record<string, unknown> | null;
  locked_total?: number | null;
  locked_total_currency?: string | null;
  locked_total_base_nzd?: number | null;
  locked_fx_rate?: number | null;
  locked_market_markup?: number | null;
  locked_zonos_dhl_markup?: number | null;
  locked_at?: string | null;
  created_at: string;
  expires_at: string;
  pricing_locked_until: string;
  pricing_status: 'locked' | 'live';
  status: string;
  current_step?: number;
  total_steps?: number;
  shopify_order_id?: string | null;
  shopify_order_number?: string | null;
  purchased_at?: string | null;
}


/**
 * Save a quote to the database
 */
export async function saveQuote(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  email?: string,
  quoteName?: string,
  customerReference?: string,
  currentStep?: number,
  totalSteps?: number,
  pricingSnapshot?: Record<string, unknown> | null,
  firstName?: string,
  lastName?: string,
  canvasImageUrl?: string | null,
  canvasImage3DUrl?: string | null,
  status?: string
): Promise<SavedQuote> {
  const response = await fetch(SAVE_QUOTE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      config,
      calculations,
      email: email || null,
      quoteName: quoteName || null,
      customerReference: customerReference || null,
      currentStep: currentStep ?? null,
      totalSteps: totalSteps ?? 7,
      pricingSnapshot: pricingSnapshot ?? null,
      firstName: firstName || null,
      lastName: lastName || null,
      canvasImageUrl: canvasImageUrl || null,
      canvasImage3DUrl: canvasImage3DUrl || null,
      clientIp: getIpDetectionCache()?.ip || null,
      ...(status ? { status } : {}),
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to save quote');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    pricingLockedUntil: data.quote.pricingLockedUntil,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
    currentStep: data.quote.currentStep,
    totalSteps: data.quote.totalSteps,
    status: data.quote.status,
  };
}

/**
 * Retrieve a quote by ID and access token
 */
export async function getQuoteById(id: string, accessToken: string): Promise<QuoteData> {
  const response = await fetch(
    `${SAVE_QUOTE_URL}?id=${encodeURIComponent(id)}&token=${encodeURIComponent(accessToken)}`,
    {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    }
  );

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to retrieve quote');
  }

  return data.quote;
}

/**
 * Update quote status (e.g., mark as completed)
 */
export async function updateQuoteStatus(
  id: string,
  accessToken: string,
  status: 'saved' | 'completed' | 'expired'
): Promise<void> {
  const response = await fetch(SAVE_QUOTE_URL, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ id, token: accessToken, status }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to update quote status');
  }
}

/**
 * Update an existing quote in place (re-save with updated config/calculations).
 * Used when a user has already saved and saves again -- avoids creating duplicates.
 */
export async function updateQuote(
  id: string,
  accessToken: string,
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  options?: {
    email?: string;
    quoteName?: string;
    customerReference?: string;
    currentStep?: number;
    totalSteps?: number;
    pricingSnapshot?: Record<string, unknown> | null;
    firstName?: string;
    lastName?: string;
    canvasImageUrl?: string | null;
    canvasImage3DUrl?: string | null;
    status?: string;
  }
): Promise<SavedQuote> {
  const response = await fetch(SAVE_QUOTE_URL, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      id,
      token: accessToken,
      config,
      calculations,
      email: options?.email || null,
      quoteName: options?.quoteName || null,
      customerReference: options?.customerReference || null,
      currentStep: options?.currentStep ?? null,
      totalSteps: options?.totalSteps ?? 7,
      pricingSnapshot: options?.pricingSnapshot ?? null,
      firstName: options?.firstName || null,
      lastName: options?.lastName || null,
      canvasImageUrl: options?.canvasImageUrl || null,
      canvasImage3DUrl: options?.canvasImage3DUrl || null,
      clientIp: getIpDetectionCache()?.ip || null,
      status: options?.status || null,
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to update quote');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    pricingLockedUntil: data.quote.pricingLockedUntil,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
    currentStep: data.quote.currentStep,
    totalSteps: data.quote.totalSteps,
    status: data.quote.status,
  };
}

/**
 * Generate a shareable quote URL with access token.
 * Includes _ab=0&_fd=0 to suppress Shopify geo-IP redirects and a hash
 * fragment fallback so params survive any server-side redirect that strips query strings.
 */
export function generateQuoteUrl(quoteId: string, accessToken: string): string {
  const baseUrl = window.location.origin;
  const url = new URL(`${baseUrl}${window.location.pathname}`);
  url.searchParams.set('quote', quoteId);
  url.searchParams.set('token', accessToken);
  url.searchParams.set('_ab', '0');
  url.searchParams.set('_fd', '0');
  const fragment = `quote=${encodeURIComponent(quoteId)}&token=${encodeURIComponent(accessToken)}`;
  return `${url.toString()}#${fragment}`;
}

/**
 * Get quote ID and token from URL if present.
 * Checks query params first, then falls back to the hash fragment
 * (which survives Shopify geo-IP redirects that strip query strings).
 */
export function getQuoteFromUrl(): { id: string; token: string } | null {
  const urlParams = new URLSearchParams(window.location.search);
  let id = urlParams.get('quote');
  let token = urlParams.get('token');

  if (!id || !token) {
    const hash = window.location.hash?.replace(/^#/, '');
    if (hash) {
      const hashParams = new URLSearchParams(hash);
      id = hashParams.get('quote');
      token = hashParams.get('token');
    }
  }

  if (!id || !token) {
    return null;
  }

  return { id, token };
}

function formatExpirationDate(expiresAt: string): string {
  const date = new Date(expiresAt);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatPricingLockDate(pricingLockedUntil: string): string {
  const date = new Date(pricingLockedUntil);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function isPricingLocked(pricingLockedUntil: string): boolean {
  return new Date(pricingLockedUntil) > new Date();
}

/**
 * Mark quote as converted to cart
 */
export async function markQuoteConverted(quoteId: string, accessToken: string): Promise<void> {
  await updateQuoteStatus(quoteId, accessToken, 'completed');
}

/**
 * Save a quote created by an admin (sales rep).
 * Customer fields (email, name) are optional. Admin metadata is attached.
 */
export async function saveQuoteAsAdmin(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  adminId: string,
  salesRepName: string,
  options?: {
    email?: string;
    firstName?: string;
    lastName?: string;
    quoteName?: string;
    customerReference?: string;
    pricingSnapshot?: Record<string, unknown> | null;
    canvasImageUrl?: string | null;
    canvasImage3DUrl?: string | null;
  }
): Promise<SavedQuote> {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const edgeFunctionUrl = `${supabaseUrl}/functions/v1/save-quote`;
  const authHeaders = await getAdminAuthHeaders();

  const response = await fetch(edgeFunctionUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...authHeaders,
    },
    body: JSON.stringify({
      config,
      calculations,
      email: options?.email || null,
      quoteName: options?.quoteName || null,
      customerReference: options?.customerReference || null,
      currentStep: 6,
      totalSteps: 7,
      pricingSnapshot: options?.pricingSnapshot ?? null,
      firstName: options?.firstName || null,
      lastName: options?.lastName || null,
      canvasImageUrl: options?.canvasImageUrl || null,
      canvasImage3DUrl: options?.canvasImage3DUrl || null,
      status: 'quote_ready',
      createdByAdminId: adminId,
      salesRepName: salesRepName,
      createdVia: 'admin_quote_builder',
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to save admin quote');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    pricingLockedUntil: data.quote.pricingLockedUntil,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
    currentStep: data.quote.currentStep,
    totalSteps: data.quote.totalSteps,
    status: data.quote.status,
  };
}

/**
 * Auto-save a quote at checkout time (for customers who never explicitly saved).
 * Creates a row with status 'checkout_pending' and no customer email so email
 * automations will not target it. The Shopify order webhook later backfills
 * customer details from the shipping address.
 */
export async function saveQuoteForCheckout(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  quoteName: string,
  pricingSnapshot?: Record<string, unknown> | null,
  canvasImageUrl?: string | null,
  canvasImage3DUrl?: string | null
): Promise<SavedQuote> {
  const response = await fetch(SAVE_QUOTE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      config,
      calculations,
      email: null,
      quoteName,
      customerReference: null,
      currentStep: 7,
      totalSteps: 7,
      pricingSnapshot: pricingSnapshot ?? null,
      firstName: null,
      lastName: null,
      canvasImageUrl: canvasImageUrl || null,
      canvasImage3DUrl: canvasImage3DUrl || null,
      status: 'checkout_pending',
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to save quote for checkout');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    pricingLockedUntil: data.quote.pricingLockedUntil,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
    currentStep: data.quote.currentStep,
    totalSteps: data.quote.totalSteps,
    status: data.quote.status,
  };
}

