import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { jsPDF } from "npm:jspdf@2.5.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers":
    "Content-Type, Authorization, X-Client-Info, Apikey",
};

// ---------- Color helpers ----------
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

// ---------- Brand defaults ----------
const DEFAULT_BRAND = {
  primaryColor: "#01312D",
  accentColor: "#BFF102",
  accentDark: "#307C31",
  textColor: "#01312D",
  mutedColor: "#64748B",
  backgroundColor: "#FFFFFF",
  logoUrl: "",
  fontFamily: "helvetica",
};
const DEFAULT_HEADER = { title: "Custom Shade Sail Quote", tagline: "Where Cool Spaces Begin" };
const DEFAULT_FOOTER = {
  line1: "Generated by ShadeSpace Professional Configurator",
  line2: "Visit shadespace.com for more information",
};

// ---------- Currency ----------
const CURRENCY_SYMBOLS: Record<string, string> = {
  NZD: "NZ$", USD: "US$", AUD: "AU$", GBP: "\u00a3", EUR: "\u20ac", CAD: "CA$",
};
function formatCurrency(amount: number, code: string): string {
  const symbol = CURRENCY_SYMBOLS[code] || code;
  return `${symbol}${(amount || 0).toFixed(2)}`;
}

function formatMeasurement(mm: number, unit: "metric" | "imperial"): string {
  if (!mm || !isFinite(mm)) return "Not provided";
  if (unit === "imperial") {
    const inches = mm * 0.0393701;
    if (inches >= 12) {
      const feet = Math.floor(inches / 12);
      const rem = inches % 12;
      const imperial = parseFloat(rem.toFixed(1)) > 0 ? `${feet}'${rem.toFixed(1)}"` : `${feet}'`;
      return `${imperial} (${Math.round(mm)}mm)`;
    }
    return `${inches.toFixed(1)}" (${Math.round(mm)}mm)`;
  }
  return `${Math.round(mm)}mm`;
}

function formatArea(mm2: number, unit: "metric" | "imperial"): string {
  if (unit === "imperial") {
    const sqft = mm2 * (0.0393701 * 0.0393701) / 144;
    const m2 = mm2 / 1000000;
    return `${sqft.toFixed(1)} ft\u00B2 (${m2.toFixed(2)} m\u00B2)`;
  }
  return `${(mm2 / 1000000).toFixed(2)} m\u00B2`;
}

function getDiagonalKeysForCorners(corners: number): string[] {
  if (corners <= 3) return ["AC"];
  if (corners === 4) return ["AC", "BD"];
  if (corners === 5) return ["AC", "BD", "CE", "DA", "EB"];
  if (corners === 6) return ["AC", "BD", "CE", "DF", "EA", "FB"];
  if (corners === 7) return ["AC", "BD", "CE", "DF", "EG", "FA", "GB"];
  if (corners === 8) return ["AC", "BD", "CE", "DF", "EG", "FH", "GA", "HB"];
  return [];
}

// ---------- PDF Builder ----------
interface PdfBlock {
  id: string;
  type: string;
  visible: boolean;
  props: Record<string, unknown>;
}

const DEFAULT_BLOCK_TYPES: Array<{ type: string; props?: Record<string, unknown> }> = [
  { type: "quoteMeta" },
  { type: "summary" },
  { type: "measurements" },
  { type: "anchorPoints" },
  { type: "hardwareBreakdown" },
  { type: "priceBreakdown" },
  { type: "pricingCallout" },
  { type: "guarantee" },
];

function normalizeBlocks(input: unknown): PdfBlock[] {
  if (!Array.isArray(input) || input.length === 0) {
    return DEFAULT_BLOCK_TYPES.map((b, i) => ({
      id: `default-${i}`,
      type: b.type,
      visible: true,
      props: b.props || {},
    }));
  }
  return input
    .filter((b) => b && typeof b === "object")
    .map((raw, i) => ({
      id: (raw as Record<string, unknown>).id as string || `b-${i}`,
      type: (raw as Record<string, unknown>).type as string || "customText",
      visible: (raw as Record<string, unknown>).visible !== false,
      props: ((raw as Record<string, unknown>).props as Record<string, unknown>) || {},
    }));
}

function isRowVisible(block: PdfBlock, rowKey: string): boolean {
  const showRows = block.props?.showRows as Record<string, boolean> | undefined;
  if (!showRows) return true;
  return showRows[rowKey] !== false;
}

interface LiveData {
  id?: string;
  quote_reference?: string | null;
  quote_name?: string | null;
  customer_first_name?: string | null;
  customer_last_name?: string | null;
  customer_email?: string | null;
  customer_reference?: string | null;
  access_token?: string | null;
  diagram_public_url?: string | null;
  diagram_3d_url?: string | null;
  created_at?: string | null;
  config_data?: Record<string, unknown> | null;
  calculations_data?: Record<string, unknown> | null;
  shopify_order_number?: string | null;
  shipping_address?: { address1?: string; address2?: string; city?: string; province?: string; zip?: string; country?: string } | null;
  estimated_weight_kg?: number | null;
  order_notes?: string | null;
}

// Layout constants
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 14;
const MARGIN_RIGHT = 14;
const MARGIN_TOP = 14;
const MARGIN_BOTTOM = 16;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

class PdfRenderer {
  private pdf: InstanceType<typeof jsPDF>;
  private y: number;
  private brand: typeof DEFAULT_BRAND;

  constructor(brand: typeof DEFAULT_BRAND) {
    this.pdf = new jsPDF("p", "mm", "a4");
    this.y = MARGIN_TOP;
    this.brand = brand;
  }

  private checkPageBreak(needed: number) {
    if (this.y + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
      this.pdf.addPage();
      this.y = MARGIN_TOP;
    }
  }

  private setColor(hex: string) {
    const [r, g, b] = hexToRgb(hex);
    this.pdf.setTextColor(r, g, b);
  }

  private setFillColor(hex: string) {
    const [r, g, b] = hexToRgb(hex);
    this.pdf.setFillColor(r, g, b);
  }

  private setDrawColor(hex: string) {
    const [r, g, b] = hexToRgb(hex);
    this.pdf.setDrawColor(r, g, b);
  }

  drawHeader(header: { title: string; tagline: string }) {
    const headerH = 18;
    this.checkPageBreak(headerH);
    this.setFillColor("#E8F5CC");
    this.pdf.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, headerH, 3, 3, "F");
    this.setDrawColor(this.brand.accentDark);
    this.pdf.setLineWidth(0.5);
    this.pdf.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, headerH, 3, 3, "S");
    this.pdf.setFont("helvetica", "bold");
    this.pdf.setFontSize(14);
    this.setColor(this.brand.primaryColor);
    this.pdf.text(header.title, MARGIN_LEFT + 6, this.y + 8);
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(9);
    this.setColor(this.brand.accentDark);
    this.pdf.text(header.tagline, MARGIN_LEFT + 6, this.y + 13);
    this.y += headerH + 6;
  }

  drawSectionTitle(title: string) {
    this.checkPageBreak(10);
    this.pdf.setFont("helvetica", "bold");
    this.pdf.setFontSize(10);
    this.setColor(this.brand.primaryColor);
    this.pdf.text(title, MARGIN_LEFT, this.y + 4);
    this.setDrawColor(this.brand.accentColor);
    this.pdf.setLineWidth(0.6);
    this.pdf.line(MARGIN_LEFT, this.y + 6, MARGIN_LEFT + CONTENT_WIDTH, this.y + 6);
    this.y += 10;
  }

  drawRow(label: string, value: string, _indent = 0) {
    this.checkPageBreak(6);
    const xLabel = MARGIN_LEFT + _indent;
    const xVal = PAGE_WIDTH - MARGIN_RIGHT;
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(9);
    this.setColor(this.brand.mutedColor);
    this.pdf.text(label, xLabel, this.y + 3);
    this.pdf.setFont("helvetica", "bold");
    this.pdf.setFontSize(9);
    this.setColor(this.brand.textColor);
    const valWidth = this.pdf.getTextWidth(value);
    this.pdf.text(value, xVal - valWidth, this.y + 3);
    this.setDrawColor("#E5E7EB");
    this.pdf.setLineWidth(0.15);
    this.pdf.line(MARGIN_LEFT, this.y + 5, PAGE_WIDTH - MARGIN_RIGHT, this.y + 5);
    this.y += 6;
  }

  drawSubRow(label: string, value: string) {
    this.checkPageBreak(5);
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(8);
    this.setColor(this.brand.mutedColor);
    this.pdf.text(label, MARGIN_LEFT + 4, this.y + 3);
    const xVal = PAGE_WIDTH - MARGIN_RIGHT;
    const valWidth = this.pdf.getTextWidth(value);
    this.pdf.text(value, xVal - valWidth, this.y + 3);
    this.y += 5;
  }

  drawCallout(label: string, price: string) {
    this.checkPageBreak(20);
    const h = 18;
    this.setFillColor(this.brand.primaryColor);
    this.pdf.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, h, 3, 3, "F");
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(9);
    this.pdf.setTextColor(255, 255, 255);
    const labelW = this.pdf.getTextWidth(label);
    this.pdf.text(label, MARGIN_LEFT + (CONTENT_WIDTH - labelW) / 2, this.y + 6);
    this.pdf.setFont("helvetica", "bold");
    this.pdf.setFontSize(14);
    const [ar, ag, ab] = hexToRgb(this.brand.accentColor);
    this.pdf.setTextColor(ar, ag, ab);
    const priceW = this.pdf.getTextWidth(price);
    this.pdf.text(price, MARGIN_LEFT + (CONTENT_WIDTH - priceW) / 2, this.y + 13);
    this.y += h + 6;
  }

  drawGuarantee(title: string, text: string) {
    this.checkPageBreak(16);
    const h = 14;
    this.setFillColor("#E8F5CC");
    this.pdf.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, h, 3, 3, "F");
    this.setDrawColor(this.brand.accentDark);
    this.pdf.setLineWidth(0.4);
    this.pdf.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, h, 3, 3, "S");
    this.pdf.setFont("helvetica", "bold");
    this.pdf.setFontSize(9);
    this.setColor(this.brand.primaryColor);
    this.pdf.text(title, MARGIN_LEFT + 4, this.y + 5);
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(8);
    this.setColor(this.brand.textColor);
    this.pdf.text(text, MARGIN_LEFT + 4, this.y + 10);
    this.y += h + 6;
  }

  addSpacer(h = 4) {
    this.y += h;
  }

  drawFooter(footer: { line1: string; line2: string }) {
    this.checkPageBreak(12);
    this.y += 6;
    this.pdf.setFont("helvetica", "normal");
    this.pdf.setFontSize(7);
    this.setColor(this.brand.mutedColor);
    const center = PAGE_WIDTH / 2;
    const l1w = this.pdf.getTextWidth(footer.line1);
    this.pdf.text(footer.line1, center - l1w / 2, this.y);
    this.y += 3.5;
    const l2w = this.pdf.getTextWidth(footer.line2);
    this.pdf.text(footer.line2, center - l2w / 2, this.y);
    this.y += 4;
  }

  forcePageBreak() {
    this.pdf.addPage();
    this.y = MARGIN_TOP;
  }

  async addImage(url: string, maxW: number, maxH: number) {
    try {
      const resp = await fetch(url);
      if (!resp.ok) return;
      const contentType = resp.headers.get("content-type") || "image/png";
      const buffer = await resp.arrayBuffer();
      const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));
      const dataUri = `data:${contentType};base64,${base64}`;
      const format = contentType.includes("png") ? "PNG" : "JPEG";

      this.checkPageBreak(maxH + 4);
      const xCenter = MARGIN_LEFT + (CONTENT_WIDTH - maxW) / 2;
      this.pdf.addImage(dataUri, format, xCenter, this.y, maxW, maxH);
      this.y += maxH + 4;
    } catch {
      // Skip image on failure
    }
  }

  getArrayBuffer(): ArrayBuffer {
    return this.pdf.output("arraybuffer");
  }
}

// ---------- Block rendering ----------
function renderBlockToPdf(
  r: PdfRenderer,
  block: PdfBlock,
  _brand: typeof DEFAULT_BRAND,
  live: LiveData,
) {
  const p = block.props || {};
  const title = (p.title as string) || "";
  const cfgData = live.config_data || null;
  const calc = live.calculations_data || null;
  const currency = (cfgData?.currency as string) || "NZD";
  const total = (calc?.totalPrice as number) ?? 650;
  const fabricLabel = (cfgData?.fabricType as string) || "Monotec 370";
  const fabricColor = (cfgData?.fabricColor as string) || "";
  const corners = (cfgData?.corners as number) ?? 4;
  const unit: "metric" | "imperial" = (cfgData?.unit as string) === "imperial" ? "imperial" : "metric";
  const measurements = (cfgData?.measurements || {}) as Record<string, number>;

  switch (block.type) {
    case "quoteMeta": {
      const heading = title || "Quote Details";
      r.drawSectionTitle(heading);
      const fullName = [live.customer_first_name, live.customer_last_name].filter(Boolean).join(" ").trim();
      const name = fullName || "See Shopify Order";
      const email = live.customer_email || "See Shopify Order";
      const qRef = live.quote_reference || "Pending";
      const date = live.created_at
        ? new Date(live.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
      const custRef = live.customer_reference || (cfgData?.customerReference as string | undefined);
      const quoteName = live.quote_name || (cfgData?.quoteName as string | undefined);
      if (isRowVisible(block, "customerName")) r.drawRow("Customer Name", name);
      if (isRowVisible(block, "email")) r.drawRow("Email", email);
      if (isRowVisible(block, "quoteReference")) r.drawRow("Quote Reference", qRef);
      if (isRowVisible(block, "quoteName") && quoteName) r.drawRow("Quote Name", quoteName);
      if (isRowVisible(block, "customerReference") && custRef) r.drawRow("Customer Reference", custRef);
      if (isRowVisible(block, "date")) r.drawRow("Date", date);
      r.addSpacer();
      break;
    }
    case "orderDetails": {
      const heading = title || "Order Details";
      r.drawSectionTitle(heading);
      const fullName = [live.customer_first_name, live.customer_last_name].filter(Boolean).join(" ").trim();
      const name = fullName || "Pending (from Shopify order)";
      const email = live.customer_email || "Pending";
      const odRef = live.quote_reference || "Pending";
      const orderNum = live.shopify_order_number || "Pending";
      const date = live.created_at
        ? new Date(live.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
      const addr = live.shipping_address;
      const addressStr = addr
        ? [addr.address1, addr.address2, addr.city, addr.province, addr.zip, addr.country].filter(Boolean).join(", ")
        : "Pending (from Shopify order)";
      const weight = live.estimated_weight_kg != null ? `${live.estimated_weight_kg} kg` : "Calculated at fulfilment";
      const notes = live.order_notes || "None";
      if (isRowVisible(block, "customerName")) r.drawRow("Customer Name", name);
      if (isRowVisible(block, "email")) r.drawRow("Email", email);
      if (isRowVisible(block, "quoteReference")) r.drawRow("Quote Reference", odRef);
      if (isRowVisible(block, "shopifyOrderNumber")) r.drawRow("Shopify Order", `#${orderNum}`);
      if (isRowVisible(block, "shippingAddress")) r.drawRow("Shipping Address", addressStr);
      if (isRowVisible(block, "weight")) r.drawRow("Estimated Weight", weight);
      if (isRowVisible(block, "orderNotes")) r.drawRow("Order Notes", notes);
      if (isRowVisible(block, "date")) r.drawRow("Date", date);
      r.addSpacer();
      break;
    }
    case "summary": {
      const heading = title || "Shade Sail Summary";
      r.drawSectionTitle(heading);
      const fabricationMethod = cfgData?.measurementOption === "adjust"
        ? "Manufactured to fit my space"
        : "Custom dimensions provided by customer";
      const edgeType = cfgData?.edgeType === "cabled" ? "Cabled Edge" : "Webbing Reinforced";
      const perimeterMm = ((calc?.perimeter as number) || 14) * 1000;
      if (isRowVisible(block, "fabricMaterial")) r.drawRow("Fabric Material", fabricLabel);
      if (isRowVisible(block, "fabricColor")) r.drawRow("Fabric Color", fabricColor);
      if (isRowVisible(block, "corners")) r.drawRow("Corners", String(corners));
      if (isRowVisible(block, "totalArea")) r.drawRow("Total Area", formatArea(((calc?.area as number) || 12.5) * 1000000, unit));
      if (isRowVisible(block, "edgePerimeter")) r.drawRow("Edge Perimeter", formatMeasurement(perimeterMm, unit));
      if (isRowVisible(block, "edgeReinforcement")) r.drawRow("Edge Reinforcement", edgeType);
      if (isRowVisible(block, "thread")) r.drawRow("Thread", "Sewn with SolarFix PTFE thread");
      if (isRowVisible(block, "fabricationMethod")) r.drawRow("Fabrication Method", fabricationMethod);
      r.addSpacer();
      break;
    }
    case "measurements": {
      const heading = title || "Precise Measurements";
      r.drawSectionTitle(heading);
      for (let i = 0; i < corners; i++) {
        const next = (i + 1) % corners;
        const key = `${String.fromCharCode(65 + i)}${String.fromCharCode(65 + next)}`;
        const mm = measurements[key];
        if (mm) r.drawRow(`Edge ${key.charAt(0)} to ${key.charAt(1)}`, formatMeasurement(mm, unit));
      }
      const diagKeys = getDiagonalKeysForCorners(corners);
      for (const key of diagKeys) {
        const mm = measurements[key];
        if (mm) r.drawRow(`Diagonal ${key.charAt(0)} to ${key.charAt(1)}`, formatMeasurement(mm, unit));
      }
      r.addSpacer();
      break;
    }
    case "anchorPoints": {
      const heading = title || "Anchor Point Configuration";
      r.drawSectionTitle(heading);
      const fixingHeights = (cfgData?.fixingHeights || []) as number[];
      const fixingTypes = (cfgData?.fixingTypes || []) as string[];
      const eyeOrientations = (cfgData?.eyeOrientations || []) as string[];
      for (let i = 0; i < corners; i++) {
        const letter = String.fromCharCode(65 + i);
        const h = fixingHeights[i] || 0;
        const t = fixingTypes[i] || "post";
        const o = eyeOrientations[i] || "horizontal";
        r.drawRow(`Corner ${letter}`, `${formatMeasurement(h, unit)}, ${t}, ${o} eye`);
      }
      r.addSpacer();
      break;
    }
    case "hardwareBreakdown": {
      const heading = title || "Corner Hardware Breakdown";
      r.drawSectionTitle(heading);
      const hwMode = (cfgData?.hardwareSelectionMode as string) || (cfgData?.measurementOption === "adjust" ? "standard" : "none");
      if (hwMode === "none") {
        r.drawRow("Hardware", "No tensioning hardware included");
      } else if (hwMode === "standard") {
        r.drawRow(`Hardware Tensioning Kit (${corners}-corner pack)`, "Included");
      } else {
        const cornerHw = (cfgData?.cornerHardware || {}) as Record<number, Array<{ name: string; sku?: string; qty: number; livePrice?: number; livePriceCurrency?: string }>>;
        for (let i = 0; i < corners; i++) {
          const letter = String.fromCharCode(65 + i);
          const lines = cornerHw[i] || [];
          const cornerTotal = lines.reduce((sum, l) => {
            const lp = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice : 0;
            return sum + lp * l.qty;
          }, 0);
          r.drawRow(`Corner ${letter}`, formatCurrency(cornerTotal, currency));
          for (const l of lines) {
            const skuPart = l.sku ? ` (${l.sku})` : "";
            const lineLive = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice * l.qty : 0;
            r.drawSubRow(`${l.qty}x ${l.name}${skuPart}`, formatCurrency(lineLive, currency));
          }
        }
      }
      r.addSpacer();
      break;
    }
    case "priceBreakdown": {
      const heading = title || "Price Breakdown";
      r.drawSectionTitle(heading);
      const hb = calc?.hardwareBreakdown as Record<string, unknown> | undefined;
      const isManual = hb?.mode === "manual" && hb?.liveCurrency === currency && (hb?.hardwareOnlyLivePrice as number) > 0;
      if (isManual) {
        const hwLive = hb!.hardwareOnlyLivePrice as number;
        r.drawRow("Shade sail", formatCurrency(total - hwLive, currency));
        r.drawRow("Hardware", formatCurrency(hwLive, currency));
      } else {
        r.drawRow("Shade sail", formatCurrency(total, currency));
      }
      r.drawRow("Total", formatCurrency(total, currency));
      r.addSpacer();
      break;
    }
    case "pricingCallout": {
      const label = title || "All-Inclusive Price to Your Door";
      r.drawCallout(label, formatCurrency(total, currency));
      break;
    }
    case "guarantee": {
      const heading = title || "Quality Guarantee";
      r.drawGuarantee(heading, "15-year Fabric & Workmanship Warranty - Weather-resistant materials - Free worldwide shipping");
      break;
    }
    case "stepSelections": {
      const heading = title || "Step-by-Step Selections";
      r.drawSectionTitle(heading);
      const manufacturing = cfgData?.measurementOption === "exact"
        ? "Manufacture Shade Sail to the Exact Dimensions I provide"
        : "Manufacture Shade Sail to fit my Space";
      const fabricationMethod = cfgData?.measurementOption === "adjust"
        ? "Manufactured to fit my space"
        : "Custom dimensions provided by customer";
      const hwMode = (cfgData?.hardwareSelectionMode as string) || (cfgData?.measurementOption === "adjust" ? "standard" : "none");
      const hwLabel = hwMode === "standard" ? `Standard tensioning kit included (${corners}-corner pack)` : hwMode === "manual" ? "Manual hardware per corner" : "No tensioning hardware";
      const fixingLabel = cfgData?.fixingPointsInstalled === true ? "Already installed" : cfgData?.fixingPointsInstalled === false ? "Planning installation" : "Not specified";
      const edgeLabel = cfgData?.edgeType === "cabled" ? "Cabled edge" : "Webbing reinforced";
      const rows: [string, string][] = [
        ["Step 1 - Manufacturing Approach", manufacturing],
        ["Step 2 - Fabrication Method", fabricationMethod],
        ["Step 3 - Number of Corners", `${corners}-corner shade sail`],
        ["Step 4 - Measurement Units", unit === "metric" ? "Metric (mm / m)" : "Imperial (in / ft)"],
        ["Step 5 - Fabric", `${fabricLabel}${fabricColor ? ` - ${fabricColor}` : ""}`],
        ["Step 6 - Edge Reinforcement", edgeLabel],
        ["Step 7 - Tensioning Hardware", hwLabel],
        ["Step 8 - Fixing Points", fixingLabel],
      ];
      for (const [label, value] of rows) {
        r.drawRow(label, value);
      }
      r.addSpacer();
      break;
    }
    case "billOfMaterials": {
      const heading = title || "Bill of Materials";
      r.drawSectionTitle(heading);
      r.drawRow(`${fabricLabel} - ${fabricColor} (${formatArea(((calc?.area as number) || 12.5) * 1000000, unit)})`, formatCurrency(total - 70, currency));
      r.drawRow("Edge reinforcement", "Included");
      r.drawRow(`Hardware Tensioning Kit (${corners}-corner pack)`, "Included");
      r.drawRow("Total (all-inclusive)", formatCurrency(total, currency));
      r.addSpacer();
      break;
    }
    case "customText": {
      const heading = p.heading as string | undefined;
      const body = p.body as string | undefined;
      if (heading) {
        r.drawSectionTitle(heading);
      }
      if (body) {
        r.drawRow("", body);
      }
      break;
    }
    case "divider": {
      r.addSpacer(2);
      break;
    }
    case "spacer": {
      r.addSpacer(Number(p.height) || 6);
      break;
    }
    case "pageBreak": {
      r.forcePageBreak();
      break;
    }
    default:
      break;
  }
}

// ---------- Main handler ----------
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const ref = url.searchParams.get("ref");
    const pdfType = url.searchParams.get("type") || "fulfilment";

    if (!ref) {
      return new Response("Missing quote reference. Please provide ?ref=QUOTE_REFERENCE", {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "text/plain" },
      });
    }

    const validTypes = ["quote", "fulfilment"];
    const resolvedType = validTypes.includes(pdfType) ? pdfType : "fulfilment";

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: quote, error: quoteErr } = await supabase
      .from("saved_quotes")
      .select(
        "id, quote_reference, quote_name, customer_first_name, customer_last_name, customer_email, customer_reference, config_data, calculations_data, diagram_public_url, diagram_3d_public_url, created_at, access_token, shopify_order_number, shipping_address, estimated_weight_kg, order_notes"
      )
      .eq("quote_reference", ref)
      .maybeSingle();

    if (quoteErr) {
      console.error("serve-order-pdf DB error:", quoteErr);
      return new Response(`Database error: ${quoteErr.message}`, {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "text/plain" },
      });
    }
    if (!quote) {
      return new Response("Quote not found. The reference may be invalid or expired.", {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "text/plain" },
      });
    }

    // Load active PDF template
    let templateRow = null;
    const { data: primaryTemplate } = await supabase
      .from("pdf_templates")
      .select("config, blocks")
      .eq("is_active", true)
      .eq("template_type", resolvedType)
      .maybeSingle();
    if (primaryTemplate) {
      templateRow = primaryTemplate;
    } else {
      const fallbackType = resolvedType === "fulfilment" ? "quote" : "fulfilment";
      const { data: fallbackTemplate } = await supabase
        .from("pdf_templates")
        .select("config, blocks")
        .eq("is_active", true)
        .eq("template_type", fallbackType)
        .maybeSingle();
      templateRow = fallbackTemplate;
    }

    const cfg = (templateRow?.config || {}) as Record<string, unknown>;
    const brand = { ...DEFAULT_BRAND, ...(cfg.brand as Record<string, string> || {}) };
    const header = { ...DEFAULT_HEADER, ...(cfg.header as Record<string, string> || {}) };
    const footer = { ...DEFAULT_FOOTER, ...(cfg.footer as Record<string, string> || {}) };
    const blocks = normalizeBlocks(templateRow?.blocks);

    const validImageUrl = (imgUrl: string | null): string | null => {
      if (!imgUrl) return null;
      if (imgUrl.includes("shopify-staged-uploads")) return null;
      return imgUrl;
    };

    const live: LiveData = {
      id: quote.id,
      quote_reference: quote.quote_reference,
      quote_name: quote.quote_name,
      customer_first_name: quote.customer_first_name,
      customer_last_name: quote.customer_last_name,
      customer_email: quote.customer_email,
      customer_reference: quote.customer_reference,
      access_token: quote.access_token,
      diagram_public_url: validImageUrl(quote.diagram_public_url),
      diagram_3d_url: validImageUrl(quote.diagram_3d_public_url),
      created_at: quote.created_at,
      config_data: quote.config_data,
      calculations_data: quote.calculations_data,
      shopify_order_number: quote.shopify_order_number,
      shipping_address: quote.shipping_address,
      estimated_weight_kg: quote.estimated_weight_kg,
      order_notes: quote.order_notes,
    };

    // Build PDF server-side
    const renderer = new PdfRenderer(brand);
    renderer.drawHeader(header);

    const visibleBlocks = blocks.filter((b) => b.visible);

    for (const block of visibleBlocks) {
      if (block.type === "diagramImage") {
        const hasPlain = live.diagram_public_url;
        const has3d = live.diagram_3d_url;
        if (hasPlain || has3d) {
          renderer.drawSectionTitle((block.props?.title as string) || "Shade Sail Diagram");
          if (hasPlain) {
            await renderer.addImage(hasPlain, 80, 60);
          }
          if (has3d) {
            await renderer.addImage(has3d, 80, 60);
          }
        }
        continue;
      }
      if (block.type === "diagram3D") {
        if (live.diagram_3d_url) {
          renderer.drawSectionTitle((block.props?.title as string) || "3D Render");
          await renderer.addImage(live.diagram_3d_url, 80, 60);
        }
        continue;
      }
      renderBlockToPdf(renderer, block, brand, live);
    }

    renderer.drawFooter(footer);

    const pdfBuffer = renderer.getArrayBuffer();
    const filename = resolvedType === "fulfilment"
      ? `shade-sail-fulfilment-${quote.quote_reference}.pdf`
      : `shade-sail-quote-${quote.quote_reference}.pdf`;

    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  } catch (err) {
    console.error("serve-order-pdf error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
