import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers":
    "Content-Type, Authorization, X-Client-Info, Apikey",
  "X-Content-Type-Options": "nosniff",
};

function htmlResponse(html: string, status = 200) {
  return new Response(html, {
    status,
    headers: { ...corsHeaders, "Content-Type": "text/html; charset=utf-8" },
  });
}

function jsonResponse(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// Minimal escapeHtml for safe rendering
function escapeHtml(str: unknown): string {
  const s = String(str ?? "");
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const ref = url.searchParams.get("ref");
    const pdfType = url.searchParams.get("type") || "fulfilment";

    if (!ref) {
      return htmlResponse(errorPage("Missing quote reference. Please provide ?ref=QUOTE_REFERENCE"), 400);
    }

    const validTypes = ["quote", "fulfilment"];
    const resolvedType = validTypes.includes(pdfType) ? pdfType : "fulfilment";

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Load quote
    const { data: quote, error: quoteErr } = await supabase
      .from("saved_quotes")
      .select(
        "id, quote_reference, quote_name, customer_first_name, customer_last_name, customer_email, customer_reference, config_data, calculations_data, diagram_public_url, diagram_3d_public_url, created_at, access_token, shopify_order_number, shipping_address, estimated_weight_kg, order_notes"
      )
      .eq("quote_reference", ref)
      .maybeSingle();

    if (quoteErr) {
      console.error("serve-order-pdf DB error:", quoteErr);
      return htmlResponse(errorPage(`Database error while loading quote. Please try again.`, quoteErr.message), 500);
    }
    if (!quote) {
      return htmlResponse(errorPage("Quote not found. The reference may be invalid or expired."), 404);
    }

    // Load active PDF template based on requested type
    let templateRow = null;
    const { data: primaryTemplate } = await supabase
      .from("pdf_templates")
      .select("config, blocks")
      .eq("is_active", true)
      .eq("template_type", resolvedType)
      .maybeSingle();
    if (primaryTemplate) {
      templateRow = primaryTemplate;
    } else {
      // Fallback: if requested type not found, try the other type
      const fallbackType = resolvedType === "fulfilment" ? "quote" : "fulfilment";
      const { data: fallbackTemplate } = await supabase
        .from("pdf_templates")
        .select("config, blocks")
        .eq("is_active", true)
        .eq("template_type", fallbackType)
        .maybeSingle();
      templateRow = fallbackTemplate;
    }

    const defaultBrand = {
      primaryColor: "#01312D",
      accentColor: "#BFF102",
      accentDark: "#307C31",
      textColor: "#01312D",
      mutedColor: "#64748B",
      backgroundColor: "#FFFFFF",
      logoUrl: "",
      fontFamily: "system-ui, -apple-system, sans-serif",
    };
    const defaultHeader = { title: "Custom Shade Sail Quote", tagline: "Where Cool Spaces Begin" };
    const defaultFooter = {
      line1: "Generated by ShadeSpace Professional Configurator",
      line2: "Visit shadespace.com for more information",
    };

    const cfg = (templateRow?.config || {}) as Record<string, unknown>;
    const brand = { ...defaultBrand, ...(cfg.brand as Record<string, string> || {}) };
    const header = { ...defaultHeader, ...(cfg.header as Record<string, string> || {}) };
    const footer = { ...defaultFooter, ...(cfg.footer as Record<string, string> || {}) };
    const layoutCfg = (cfg.layout || {}) as Record<string, unknown>;
    const density = (layoutCfg.density as string) || "comfortable";
    const paper = (cfg.paper as string) || "A4";

    // Blocks
    const blocks = normalizeBlocks(templateRow?.blocks);

    // Filter out expired staged upload URLs (they expire after a few hours)
    const validImageUrl = (url: string | null): string | null => {
      if (!url) return null;
      if (url.includes("shopify-staged-uploads")) return null;
      return url;
    };

    // Build live data for template rendering
    const live = {
      id: quote.id,
      quote_reference: quote.quote_reference,
      quote_name: quote.quote_name,
      customer_first_name: quote.customer_first_name,
      customer_last_name: quote.customer_last_name,
      customer_email: quote.customer_email,
      customer_reference: quote.customer_reference,
      access_token: quote.access_token,
      diagram_public_url: validImageUrl(quote.diagram_public_url),
      diagram_3d_url: validImageUrl(quote.diagram_3d_public_url),
      created_at: quote.created_at,
      config_data: quote.config_data,
      calculations_data: quote.calculations_data,
      shopify_order_number: quote.shopify_order_number,
      shipping_address: quote.shipping_address,
      estimated_weight_kg: quote.estimated_weight_kg,
      order_notes: quote.order_notes,
    };

    const quoteHtml = buildQuoteHtml(brand, header, footer, blocks, live, density);
    const customerName = [quote.customer_first_name, quote.customer_last_name].filter(Boolean).join(" ").trim() || "Customer";
    const filename = resolvedType === "fulfilment"
      ? `shade-sail-fulfilment-${quote.quote_reference}.pdf`
      : `shade-sail-quote-${quote.quote_reference}.pdf`;

    const page = renderDownloadPage(quoteHtml, filename, customerName, quote.quote_reference, paper, resolvedType);
    return htmlResponse(page);
  } catch (err) {
    console.error("serve-order-pdf error:", err);
    return jsonResponse({ error: err instanceof Error ? err.message : String(err) }, 500);
  }
});

// --- Template / block rendering (server-side port of pdfHtmlPreview.ts) ---

interface PdfBlock {
  id: string;
  type: string;
  visible: boolean;
  props: Record<string, unknown>;
}

const DEFAULT_BLOCK_TYPES: Array<{ type: string; props?: Record<string, unknown> }> = [
  { type: "quoteMeta" },
  { type: "diagramImage" },
  { type: "summary" },
  { type: "measurements" },
  { type: "anchorPoints" },
  { type: "hardwareBreakdown" },
  { type: "stepSelections" },
  { type: "priceBreakdown" },
  { type: "pricingCallout" },
  { type: "guarantee" },
];

function normalizeBlocks(input: unknown): PdfBlock[] {
  if (!Array.isArray(input) || input.length === 0) {
    return DEFAULT_BLOCK_TYPES.map((b, i) => ({
      id: `default-${i}`,
      type: b.type,
      visible: true,
      props: b.props || {},
    }));
  }
  return input
    .filter((b) => b && typeof b === "object")
    .map((raw, i) => ({
      id: (raw as Record<string, unknown>).id as string || `b-${i}`,
      type: (raw as Record<string, unknown>).type as string || "customText",
      visible: (raw as Record<string, unknown>).visible !== false,
      props: ((raw as Record<string, unknown>).props as Record<string, unknown>) || {},
    }));
}

const BLOCK_LABELS: Record<string, string> = {
  summary: "Configuration Summary",
  measurements: "Measurements",
  anchorPoints: "Anchor Points",
  hardwareBreakdown: "Hardware Breakdown",
  priceBreakdown: "Price Breakdown",
  guarantee: "Quality Guarantee",
  pricingCallout: "Total Price",
  quoteMeta: "Quote Details",
  orderDetails: "Order Details",
  stepSelections: "Step-by-Step Selections",
  diagramImage: "Shade Sail Diagram",
  diagram3D: "3D Render",
  billOfMaterials: "Bill of Materials",
  resumeButton: "Resume Configuration",
  customText: "Custom Text",
  customImage: "Custom Image",
  customHtml: "Custom HTML",
  divider: "Divider",
  spacer: "Spacer",
  pageBreak: "Page Break",
};

const CURRENCY_SYMBOLS: Record<string, string> = {
  NZD: "NZ$", USD: "US$", AUD: "AU$", GBP: "\u00a3", EUR: "\u20ac", CAD: "CA$",
};

function formatCurrency(amount: number, code: string): string {
  const symbol = CURRENCY_SYMBOLS[code] || code;
  return `${symbol}${(amount || 0).toFixed(2)}`;
}

function formatMeasurement(mm: number, unit: "metric" | "imperial"): string {
  if (!mm || !isFinite(mm)) return "Not provided";
  if (unit === "imperial") {
    const inches = mm * 0.0393701;
    if (inches >= 12) {
      const feet = Math.floor(inches / 12);
      const rem = inches % 12;
      const imperial = parseFloat(rem.toFixed(1)) > 0 ? `${feet}'${rem.toFixed(1)}"` : `${feet}'`;
      return `${imperial} (${Math.round(mm)}mm)`;
    }
    return `${inches.toFixed(1)}" (${Math.round(mm)}mm)`;
  }
  return `${Math.round(mm)}mm`;
}

function formatArea(mm2: number, unit: "metric" | "imperial"): string {
  if (unit === "imperial") {
    const sqft = mm2 * (0.0393701 * 0.0393701) / 144;
    const m2 = mm2 / 1000000;
    return `${sqft.toFixed(1)} ft&sup2; (${m2.toFixed(2)} m&sup2;)`;
  }
  return `${(mm2 / 1000000).toFixed(2)} m&sup2;`;
}

function getDiagonalKeysForCorners(corners: number): string[] {
  if (corners <= 3) return ["AC"];
  if (corners === 4) return ["AC", "BD"];
  if (corners === 5) return ["AC", "BD", "CE", "DA", "EB"];
  if (corners === 6) return ["AC", "BD", "CE", "DF", "EA", "FB"];
  if (corners === 7) return ["AC", "BD", "CE", "DF", "EG", "FA", "GB"];
  if (corners === 8) return ["AC", "BD", "CE", "DF", "EG", "FH", "GA", "HB"];
  return [];
}

interface LiveData {
  id?: string;
  quote_reference?: string | null;
  quote_name?: string | null;
  customer_first_name?: string | null;
  customer_last_name?: string | null;
  customer_email?: string | null;
  customer_reference?: string | null;
  access_token?: string | null;
  diagram_public_url?: string | null;
  diagram_3d_url?: string | null;
  created_at?: string | null;
  config_data?: Record<string, unknown> | null;
  calculations_data?: Record<string, unknown> | null;
  shopify_order_number?: string | null;
  shipping_address?: { address1?: string; address2?: string; city?: string; province?: string; zip?: string; country?: string } | null;
  estimated_weight_kg?: number | null;
  order_notes?: string | null;
}

function isRowVisible(block: PdfBlock, rowKey: string): boolean {
  const showRows = block.props?.showRows as Record<string, boolean> | undefined;
  if (!showRows) return true;
  return showRows[rowKey] !== false;
}

function renderBlock(block: PdfBlock, brand: Record<string, string>, live: LiveData): string {
  const p = block.props || {};
  const title = (p.title as string) || BLOCK_LABELS[block.type] || "";
  const cfgData = live.config_data || null;
  const calc = live.calculations_data || null;
  const currency = (cfgData?.currency as string) || "NZD";
  const total = (calc?.totalPrice as number) ?? 650;
  const fabricLabel = (cfgData?.fabricType as string) || "Monotec 370";
  const fabricColor = (cfgData?.fabricColor as string) || "";
  const corners = (cfgData?.corners as number) ?? 4;
  const unit: "metric" | "imperial" = (cfgData?.unit as string) === "imperial" ? "imperial" : "metric";
  const measurements = (cfgData?.measurements || {}) as Record<string, number>;

  switch (block.type) {
    case "summary": {
      const fabricationMethod = cfgData?.measurementOption === "adjust"
        ? "Manufactured to fit my space"
        : "Custom dimensions provided by customer";
      const edgeType = cfgData?.edgeType === "cabled" ? "Cabled Edge" : "Webbing Reinforced";
      const perimeterMm = ((calc?.perimeter as number) || 14) * 1000;
      const sRows: string[] = [];
      if (isRowVisible(block, "fabricMaterial")) sRows.push(`<div class="row"><span class="muted">Fabric Material</span><span class="val">${escapeHtml(fabricLabel)}</span></div>`);
      if (isRowVisible(block, "fabricColor")) sRows.push(`<div class="row"><span class="muted">Fabric Color</span><span class="val">${escapeHtml(fabricColor)}</span></div>`);
      if (isRowVisible(block, "corners")) sRows.push(`<div class="row"><span class="muted">Corners</span><span class="val">${corners}</span></div>`);
      if (isRowVisible(block, "totalArea")) sRows.push(`<div class="row"><span class="muted">Total Area</span><span class="val">${formatArea(((calc?.area as number) || 12.5) * 1000000, unit)}</span></div>`);
      if (isRowVisible(block, "edgePerimeter")) sRows.push(`<div class="row"><span class="muted">Edge Perimeter</span><span class="val">${formatMeasurement(perimeterMm, unit)}</span></div>`);
      if (isRowVisible(block, "edgeReinforcement")) sRows.push(`<div class="row"><span class="muted">Edge Reinforcement</span><span class="val">${edgeType}</span></div>`);
      if (isRowVisible(block, "thread")) sRows.push(`<div class="row"><span class="muted">Thread</span><span class="val">Sewn with SolarFix&reg; PTFE thread</span></div>`);
      if (isRowVisible(block, "fabricationMethod")) sRows.push(`<div class="row"><span class="muted">Fabrication Method</span><span class="val">${escapeHtml(fabricationMethod)}</span></div>`);
      return `<h2>${escapeHtml(title)}</h2>${sRows.join("")}`;
    }
    case "measurements": {
      const edges: string[] = [];
      for (let i = 0; i < corners; i++) {
        const next = (i + 1) % corners;
        const key = `${String.fromCharCode(65 + i)}${String.fromCharCode(65 + next)}`;
        const mm = measurements[key];
        if (mm) edges.push(`<div class="row"><span class="muted">Edge ${key.charAt(0)} to ${key.charAt(1)}</span><span class="val">${formatMeasurement(mm, unit)}</span></div>`);
      }
      const diagonals: string[] = [];
      for (const key of getDiagonalKeysForCorners(corners)) {
        const mm = measurements[key];
        if (mm) diagonals.push(`<div class="row"><span class="muted">Diagonal ${key.charAt(0)} to ${key.charAt(1)}</span><span class="val">${formatMeasurement(mm, unit)}</span></div>`);
      }
      return `<h2>${escapeHtml(title)}</h2>
        <div style="margin-bottom:10px;"><div style="font-weight:700;color:${brand.accentDark};font-size:12px;margin-bottom:4px;">Edge Lengths</div>${edges.join("") || '<div class="row"><span class="muted">No edge measurements</span></div>'}</div>
        ${diagonals.length > 0 ? `<div><div style="font-weight:700;color:${brand.accentDark};font-size:12px;margin-bottom:4px;">Diagonal Lengths</div>${diagonals.join("")}</div>` : ""}`;
    }
    case "anchorPoints": {
      const fixingHeights = (cfgData?.fixingHeights || []) as number[];
      const fixingTypes = (cfgData?.fixingTypes || []) as string[];
      const eyeOrientations = (cfgData?.eyeOrientations || []) as string[];
      const rows = fixingHeights.slice(0, corners).map((h, i) => {
        const letter = String.fromCharCode(65 + i);
        const t = fixingTypes[i] || "post";
        const o = eyeOrientations[i] || "horizontal";
        return `<div class="row"><span class="muted">Corner ${letter}</span><span class="val">${formatMeasurement(h || 0, unit)}, ${t}, ${o} eye</span></div>`;
      }).join("");
      return `<h2>${escapeHtml(title)}</h2>${rows || '<div class="row"><span class="muted">Not specified</span></div>'}`;
    }
    case "hardwareBreakdown": {
      const hwMode = (cfgData?.hardwareSelectionMode as string) || (cfgData?.measurementOption === "adjust" ? "standard" : "none");
      if (hwMode === "none") {
        return `<h2>${escapeHtml(title)}</h2><div class="row"><span class="muted">No tensioning hardware included with this order.</span></div>`;
      }
      if (hwMode === "standard") {
        return `<h2>${escapeHtml(title)}</h2>
          <div class="row"><span class="muted">Hardware Tensioning Kit (${corners}-corner pack)</span><span class="val" style="color:#307C31;">Included</span></div>`;
      }
      const cornerHw = (cfgData?.cornerHardware || {}) as Record<number, Array<{ name: string; sku?: string; qty: number; livePrice?: number; livePriceCurrency?: string }>>;
      const rows: string[] = [];
      for (let i = 0; i < corners; i++) {
        const letter = String.fromCharCode(65 + i);
        const lines = cornerHw[i] || [];
        const cornerTotal = lines.reduce((sum, l) => {
          const lp = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice : 0;
          return sum + lp * l.qty;
        }, 0);
        rows.push(`<div style="padding:8px 0;border-bottom:1px solid #E5E7EB;">
          <div style="display:flex;justify-content:space-between;font-weight:700;"><span>Corner ${letter}</span><span>${formatCurrency(cornerTotal, currency)}</span></div>
          ${lines.length === 0 ? `<div style="padding-left:12px;font-size:11px;color:${brand.mutedColor};">No hardware selected</div>` : lines.map(l => {
            const skuPart = l.sku ? ` (${l.sku})` : "";
            const lineLive = l.livePriceCurrency === currency && l.livePrice != null ? l.livePrice * l.qty : 0;
            return `<div style="display:flex;justify-content:space-between;padding-left:12px;font-size:11px;color:${brand.mutedColor};"><span>${l.qty}x ${escapeHtml(l.name)}${escapeHtml(skuPart)}</span><span>${formatCurrency(lineLive, currency)}</span></div>`;
          }).join("")}
        </div>`);
      }
      return `<h2>${escapeHtml(title)}</h2>${rows.join("")}`;
    }
    case "priceBreakdown": {
      const hb = calc?.hardwareBreakdown as Record<string, unknown> | undefined;
      const isManual = hb?.mode === "manual" && hb?.liveCurrency === currency && (hb?.hardwareOnlyLivePrice as number) > 0;
      const rows: string[] = [];
      if (isManual) {
        const hwLive = hb!.hardwareOnlyLivePrice as number;
        rows.push(`<div class="row"><span class="muted">Shade sail</span><span class="val">${formatCurrency(total - hwLive, currency)}</span></div>`);
        rows.push(`<div class="row"><span class="muted">Hardware</span><span class="val">${formatCurrency(hwLive, currency)}</span></div>`);
      } else {
        rows.push(`<div class="row"><span class="muted">Shade sail</span><span class="val">${formatCurrency(total, currency)}</span></div>`);
      }
      rows.push(`<div class="row"><span class="val">Total</span><span class="val">${formatCurrency(total, currency)}</span></div>`);
      return `<h2>${escapeHtml(title)}</h2>${rows.join("")}`;
    }
    case "guarantee":
      return `<div class="guarantee"><div style="font-weight:700;margin-bottom:6px;">${escapeHtml(title)}</div>
        <div style="font-size:12px;">15-year Fabric &amp; Workmanship Warranty &middot; Weather-resistant materials &middot; Free worldwide shipping</div></div>`;
    case "pricingCallout":
      return `<div class="callout"><div style="font-size:12px;opacity:.85;">${escapeHtml(title)}</div><div class="price">${formatCurrency(total, currency)}</div></div>`;
    case "quoteMeta": {
      const fullName = [live.customer_first_name, live.customer_last_name].filter(Boolean).join(" ").trim();
      const name = fullName || "See Shopify Order";
      const email = live.customer_email || "See Shopify Order";
      const qRef = live.quote_reference || "Pending";
      const date = live.created_at
        ? new Date(live.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
      const custRef = live.customer_reference || (cfgData?.customerReference as string | undefined);
      const quoteName = live.quote_name || (cfgData?.quoteName as string | undefined);
      const qmRows: string[] = [];
      if (isRowVisible(block, "customerName")) qmRows.push(`<div class="row"><span class="muted">Customer Name</span><span class="val">${escapeHtml(name)}</span></div>`);
      if (isRowVisible(block, "email")) qmRows.push(`<div class="row"><span class="muted">Email</span><span class="val">${escapeHtml(email)}</span></div>`);
      if (isRowVisible(block, "quoteReference")) qmRows.push(`<div class="row"><span class="muted">Quote Reference</span><span class="val">${escapeHtml(qRef)}</span></div>`);
      if (isRowVisible(block, "quoteName") && quoteName) qmRows.push(`<div class="row"><span class="muted">Quote Name</span><span class="val">${escapeHtml(quoteName)}</span></div>`);
      if (isRowVisible(block, "customerReference") && custRef) qmRows.push(`<div class="row"><span class="muted">Customer Reference</span><span class="val">${escapeHtml(custRef)}</span></div>`);
      if (isRowVisible(block, "date")) qmRows.push(`<div class="row"><span class="muted">Date</span><span class="val">${escapeHtml(date)}</span></div>`);
      return `<h2>${escapeHtml(title)}</h2>${qmRows.join("")}`;
    }
    case "orderDetails": {
      const fullName = [live.customer_first_name, live.customer_last_name].filter(Boolean).join(" ").trim();
      const name = fullName || "Pending (from Shopify order)";
      const email = live.customer_email || "Pending";
      const odRef = live.quote_reference || "Pending";
      const orderNum = live.shopify_order_number || "Pending";
      const date = live.created_at
        ? new Date(live.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
      const addr = live.shipping_address;
      const addressStr = addr
        ? [addr.address1, addr.address2, addr.city, addr.province, addr.zip, addr.country].filter(Boolean).join(", ")
        : "Pending (from Shopify order)";
      const weight = live.estimated_weight_kg != null ? `${live.estimated_weight_kg} kg` : "Calculated at fulfilment";
      const notes = live.order_notes || "None";
      const odRows: string[] = [];
      if (isRowVisible(block, "customerName")) odRows.push(`<div class="row"><span class="muted">Customer Name</span><span class="val">${escapeHtml(name)}</span></div>`);
      if (isRowVisible(block, "email")) odRows.push(`<div class="row"><span class="muted">Email</span><span class="val">${escapeHtml(email)}</span></div>`);
      if (isRowVisible(block, "quoteReference")) odRows.push(`<div class="row"><span class="muted">Quote Reference</span><span class="val">${escapeHtml(odRef)}</span></div>`);
      if (isRowVisible(block, "shopifyOrderNumber")) odRows.push(`<div class="row"><span class="muted">Shopify Order</span><span class="val">#${escapeHtml(orderNum)}</span></div>`);
      if (isRowVisible(block, "shippingAddress")) odRows.push(`<div class="row"><span class="muted">Shipping Address</span><span class="val">${escapeHtml(addressStr)}</span></div>`);
      if (isRowVisible(block, "weight")) odRows.push(`<div class="row"><span class="muted">Estimated Weight</span><span class="val">${escapeHtml(weight)}</span></div>`);
      if (isRowVisible(block, "orderNotes")) odRows.push(`<div class="row"><span class="muted">Order Notes</span><span class="val">${escapeHtml(notes)}</span></div>`);
      if (isRowVisible(block, "date")) odRows.push(`<div class="row"><span class="muted">Date</span><span class="val">${escapeHtml(date)}</span></div>`);
      return `<h2>${escapeHtml(title)}</h2>${odRows.join("")}`;
    }
    case "stepSelections": {
      const manufacturing = cfgData?.measurementOption === "exact"
        ? "Manufacture Shade Sail to the Exact Dimensions I provide"
        : "Manufacture Shade Sail to fit my Space";
      const fabricationMethod = cfgData?.measurementOption === "adjust"
        ? "Manufactured to fit my space"
        : "Custom dimensions provided by customer";
      const hwMode = (cfgData?.hardwareSelectionMode as string) || (cfgData?.measurementOption === "adjust" ? "standard" : "none");
      const hwLabel = hwMode === "standard" ? `Standard tensioning kit included (${corners}-corner pack)` : hwMode === "manual" ? "Manual hardware per corner" : "No tensioning hardware";
      const fixingLabel = cfgData?.fixingPointsInstalled === true ? "Already installed" : cfgData?.fixingPointsInstalled === false ? "Planning installation" : "Not specified";
      const edgeLabel = cfgData?.edgeType === "cabled" ? "Cabled edge" : "Webbing reinforced";
      const rows: [string, string][] = [
        ["Manufacturing Approach", manufacturing],
        ["Fabrication Method", fabricationMethod],
        ["Number of Corners", `${corners}-corner shade sail`],
        ["Measurement Units", unit === "metric" ? "Metric (mm / m)" : "Imperial (in / ft)"],
        ["Fabric", `${fabricLabel}${fabricColor ? ` - ${fabricColor}` : ""}`],
        ["Edge Reinforcement", edgeLabel],
        ["Tensioning Hardware", hwLabel],
        ["Fixing Points", fixingLabel],
      ];
      return `<h2>${escapeHtml(title)}</h2>${rows.map(([label, value], idx) => `<div class="row"><span class="muted">Step ${idx + 1} - ${escapeHtml(label)}</span><span class="val">${escapeHtml(value)}</span></div>`).join("")}`;
    }
    case "diagramImage": {
      const mw = Number(p.maxWidth) || 520;
      if (live.diagram_public_url && live.diagram_3d_url) {
        const halfW = Math.floor(mw / 2) - 8;
        return `<h2>${escapeHtml(title)}</h2>
          <div style="display:flex;gap:16px;justify-content:center;align-items:flex-start;flex-wrap:wrap;">
            <div style="flex:1;min-width:200px;max-width:${halfW}px;text-align:center;">
              <img src="${escapeHtml(live.diagram_public_url)}" alt="Plan view" style="width:100%;border:1px solid #E2E8F0;border-radius:8px;padding:8px;background:#fff;" />
              <div style="font-size:11px;color:${brand.mutedColor};margin-top:6px;">Plan View</div>
            </div>
            <div style="flex:1;min-width:200px;max-width:${halfW}px;text-align:center;">
              <img src="${escapeHtml(live.diagram_3d_url)}" alt="3D view" style="width:100%;border:1px solid #E2E8F0;border-radius:8px;padding:8px;background:#fff;" />
              <div style="font-size:11px;color:${brand.mutedColor};margin-top:6px;">3D View</div>
            </div>
          </div>`;
      }
      if (live.diagram_public_url) {
        return `<h2>${escapeHtml(title)}</h2>
          <div style="text-align:center;"><img src="${escapeHtml(live.diagram_public_url)}" alt="Shade sail diagram" style="max-width:${mw}px;width:100%;border:1px solid #E2E8F0;border-radius:8px;padding:10px;background:#fff;" /></div>`;
      }
      return `<h2>${escapeHtml(title)}</h2><div style="text-align:center;padding:16px;color:${brand.mutedColor};font-size:12px;">No diagram available</div>`;
    }
    case "diagram3D": {
      const mw3d = Number(p.maxWidth) || 520;
      if (live.diagram_3d_url) {
        return `<h2>${escapeHtml(title)}</h2>
          <div style="text-align:center;"><img src="${escapeHtml(live.diagram_3d_url)}" alt="3D render" style="max-width:${mw3d}px;width:100%;border:1px solid #E2E8F0;border-radius:8px;padding:10px;background:#fff;" /></div>`;
      }
      return "";
    }
    case "billOfMaterials":
      return `<h2>${escapeHtml(title)}</h2>
        <div class="row"><span class="muted">${escapeHtml(fabricLabel)} - ${escapeHtml(fabricColor)} (${formatArea(((calc?.area as number) || 12.5) * 1000000, unit)})</span><span class="val">${formatCurrency(total - 70, currency)}</span></div>
        <div class="row"><span class="muted">Edge reinforcement</span><span class="val">Included</span></div>
        <div class="row"><span class="muted">Hardware Tensioning Kit (${corners}-corner pack)</span><span class="val">Included</span></div>
        <div class="row"><span class="val">Total (all-inclusive)</span><span class="val">${formatCurrency(total, currency)}</span></div>`;
    case "customText": {
      const align = (p.align as string) || "left";
      const heading = p.heading ? `<div style="font-weight:700;margin-bottom:6px;color:${brand.primaryColor};">${escapeHtml(p.heading)}</div>` : "";
      return `<div style="margin:12px 0;text-align:${align};font-size:13px;">${heading}<div>${escapeHtml(p.body || "")}</div></div>`;
    }
    case "customImage":
      return p.url ? `<div style="margin:12px 0;text-align:center;"><img src="${escapeHtml(p.url)}" alt="${escapeHtml(p.alt || "")}" style="max-width:${Number(p.width) || 400}px;width:100%;" /></div>` : "";
    case "divider":
      return `<hr style="border:none;border-top:${Number(p.thickness) || 1}px solid ${brand.mutedColor};opacity:0.4;margin:8px 0;" />`;
    case "spacer":
      return `<div style="height:${Number(p.height) || 16}px;"></div>`;
    case "pageBreak":
      return `<div data-pagebreak="1" style="margin:16px 0;height:1px;"></div>`;
    default:
      return "";
  }
}

function getBlockColumn(block: PdfBlock): "full" | "left" | "right" {
  const col = block.props?.column as string | undefined;
  if (col === "left") return "left";
  if (col === "right") return "right";
  return "full";
}

function buildQuoteHtml(
  brand: Record<string, string>,
  header: { title: string; tagline: string },
  footer: { line1: string; line2: string },
  blocks: PdfBlock[],
  live: LiveData,
  density: string,
): string {
  const visibleBlocks = blocks.filter((b) => b.visible);

  // Render blocks (handling two-column layout)
  const rendered: string[] = [];
  let leftBuf: string[] = [];
  let rightBuf: string[] = [];
  const flush = () => {
    if (leftBuf.length === 0 && rightBuf.length === 0) return;
    rendered.push(`<div class="two-col"><div class="col">${leftBuf.join("")}</div><div class="col">${rightBuf.join("")}</div></div>`);
    leftBuf = [];
    rightBuf = [];
  };
  for (const block of visibleBlocks) {
    const html = renderBlock(block, brand, live);
    if (!html) continue;
    const col = getBlockColumn(block);
    if (col === "full") {
      flush();
      rendered.push(`<div class="block-wrap">${html}</div>`);
    } else if (col === "left") {
      leftBuf.push(`<div class="block-wrap">${html}</div>`);
    } else {
      rightBuf.push(`<div class="block-wrap">${html}</div>`);
    }
  }
  flush();

  const presets: Record<string, { body: number; title: number; tagline: number; h2: number; row: number; rowPad: number; small: number; priceLg: number; sectionMargin: number; twoColGap: number }> = {
    comfortable: { body: 14, title: 22, tagline: 12, h2: 16, row: 13, rowPad: 6, small: 11, priceLg: 22, sectionMargin: 20, twoColGap: 16 },
    compact: { body: 13, title: 18, tagline: 11, h2: 14, row: 12, rowPad: 4, small: 10, priceLg: 18, sectionMargin: 14, twoColGap: 12 },
    ultra: { body: 12, title: 16, tagline: 10, h2: 12, row: 11, rowPad: 3, small: 9, priceLg: 16, sectionMargin: 10, twoColGap: 8 },
  };
  const p = presets[density] || presets.comfortable;

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
    body { width:688px; margin:0; padding:0; background:${brand.backgroundColor}; font-family:${brand.fontFamily || "system-ui, -apple-system, sans-serif"}; color:${brand.textColor}; font-size:${p.body}px; line-height:1.45; box-sizing:border-box; overflow-wrap:anywhere; }
    *, *::before, *::after { box-sizing:border-box; }
    .header { display:flex; align-items:center; gap:12px; padding:16px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${brand.accentColor} 100%); border:2px solid ${brand.accentDark}; margin-bottom:16px; }
    .header .meta { flex:1; }
    .logo-img { max-height:40px; max-width:180px; object-fit:contain; }
    .title { font-size:${p.title}px; font-weight:700; color:${brand.primaryColor}; margin:0; }
    .tagline { font-size:${p.tagline}px; color:${brand.accentDark}; margin:4px 0 0 0; }
    h2 { font-size:${p.h2}px; color:${brand.primaryColor}; border-bottom:2px solid ${brand.accentColor}; padding-bottom:${Math.max(2, p.rowPad - 1)}px; margin:${p.sectionMargin}px 0 ${Math.max(6, Math.round(p.sectionMargin / 2))}px; }
    .row { display:flex; justify-content:space-between; align-items:flex-start; padding:${p.rowPad}px 0; border-bottom:1px solid #E5E7EB; font-size:${p.row}px; gap:10px; }
    .row > .muted, .row > .val { min-width:0; overflow-wrap:anywhere; word-break:break-word; }
    .row > .muted { flex:1 1 auto; }
    .row > .val { flex:0 1 auto; min-width:0; }
    .muted { color:${brand.mutedColor}; }
    .val { color:${brand.textColor}; font-weight:600; text-align:right; }
    .callout { margin-top:${p.sectionMargin}px; padding:${Math.max(10, p.rowPad * 2 + 6)}px; border-radius:12px; background:${brand.primaryColor}; color:#fff; text-align:center; }
    .callout .price { font-size:${p.priceLg}px; font-weight:700; color:${brand.accentColor}; }
    .guarantee { margin-top:${p.sectionMargin}px; padding:${Math.max(10, p.rowPad * 2 + 6)}px; border-radius:12px; background:linear-gradient(135deg, #F3FFE3 0%, ${brand.accentColor} 20%); border:2px solid ${brand.accentDark}; color:${brand.primaryColor}; font-size:${p.row}px; }
    .footer { margin-top:24px; text-align:center; font-size:${p.small}px; color:${brand.mutedColor}; }
    hr { border:none; border-top:1px solid ${brand.mutedColor}; margin:8px 0; opacity:0.4; }
    .two-col { display:grid; grid-template-columns:1fr 1fr; gap:${p.twoColGap}px; align-items:start; margin-top:4px; }
    .two-col > .col { min-width:0; overflow-wrap:anywhere; }
    .two-col h2 { margin-top:8px; }
    .block-wrap { display:block; }
    img { display:inline-block; max-width:100%; }
  </style></head><body>
    <div class="header">
      ${brand.logoUrl ? `<img class="logo-img" src="${escapeHtml(brand.logoUrl)}" alt="logo" />` : ""}
      <div class="meta">
        <h1 class="title">${escapeHtml(header.title)}</h1>
        <p class="tagline">${escapeHtml(header.tagline)}</p>
      </div>
    </div>
    ${rendered.join("")}
    <div class="footer">
      <div>${escapeHtml(footer.line1)}</div>
      <div>${escapeHtml(footer.line2)}</div>
    </div>
  </body></html>`;
}

function renderDownloadPage(quoteHtml: string, filename: string, customerName: string, quoteRef: string, paper: string, pdfType: string): string {
  const escapedHtml = quoteHtml.replace(/`/g, "\\`").replace(/<\/script/g, "<\\/script");
  const pageTitle = pdfType === "fulfilment"
    ? `Fulfilment Order - ${escapeHtml(quoteRef)}`
    : `Shade Sail Quote - ${escapeHtml(quoteRef)}`;
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${pageTitle}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; background: #F8FAFC; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 40px 20px; }
    .container { text-align: center; max-width: 500px; }
    .icon { width: 64px; height: 64px; margin: 0 auto 24px; background: #01312D; border-radius: 16px; display: flex; align-items: center; justify-content: center; }
    .icon svg { width: 32px; height: 32px; fill: #BFF102; }
    h1 { font-size: 24px; color: #01312D; margin-bottom: 8px; }
    .subtitle { color: #64748B; font-size: 14px; margin-bottom: 32px; }
    .status { padding: 16px 24px; background: white; border-radius: 12px; border: 1px solid #E2E8F0; margin-bottom: 16px; }
    .status.generating { border-color: #BFF102; }
    .status.done { border-color: #22C55E; background: #F0FDF4; }
    .status.error { border-color: #EF4444; background: #FEF2F2; }
    .status-text { font-size: 14px; color: #334155; }
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid #E2E8F0; border-top-color: #01312D; border-radius: 50%; animation: spin 0.8s linear infinite; margin-right: 8px; vertical-align: middle; }
    @keyframes spin { to { transform: rotate(360deg); } }
    .btn { display: inline-block; margin-top: 16px; padding: 12px 24px; background: #01312D; color: #BFF102; border: none; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; text-decoration: none; }
    .btn:hover { opacity: 0.9; }
    .btn.hidden { display: none; }
    .detail { font-size: 12px; color: #94A3B8; margin-top: 8px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="icon">
      <svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8" fill="none" stroke="#01312D" stroke-width="1.5"/></svg>
    </div>
    <h1>${pdfType === "fulfilment" ? "Fulfilment Order PDF" : "Shade Sail Quote PDF"}</h1>
    <p class="subtitle">Customer: ${escapeHtml(customerName)} &middot; Ref: ${escapeHtml(quoteRef)}</p>
    <div class="status generating" id="status">
      <span class="status-text"><span class="spinner"></span>Generating PDF...</span>
    </div>
    <button class="btn hidden" id="downloadBtn" onclick="downloadAgain()">Download Again</button>
    <p class="detail">The PDF will download automatically. If it doesn't start, click the button above.</p>
  </div>

  <iframe id="renderFrame" style="position:fixed;left:-10000px;top:0;width:688px;height:1123px;border:0;opacity:0;pointer-events:none;"></iframe>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
  <script>
    const QUOTE_HTML = \`${escapedHtml}\`;
    const FILENAME = ${JSON.stringify(filename)};
    const PAPER = ${JSON.stringify(paper)};

    let generatedBlob = null;

    function setStatus(type, text) {
      const el = document.getElementById('status');
      el.className = 'status ' + type;
      el.querySelector('.status-text').innerHTML = type === 'generating'
        ? '<span class="spinner"></span>' + text
        : text;
      if (type === 'done' || type === 'error') {
        document.getElementById('downloadBtn').classList.remove('hidden');
      }
    }

    function downloadAgain() {
      if (generatedBlob) {
        const url = URL.createObjectURL(generatedBlob);
        const a = document.createElement('a');
        a.href = url;
        a.download = FILENAME;
        a.click();
        URL.revokeObjectURL(url);
      }
    }

    async function generatePdf() {
      try {
        const iframe = document.getElementById('renderFrame');
        const doc = iframe.contentDocument;
        doc.open();
        doc.write(QUOTE_HTML);
        doc.close();

        // Wait for fonts and images (with 5s timeout per image to avoid hanging)
        await new Promise(r => setTimeout(r, 500));
        await Promise.all(
          Array.from(doc.images).map(img => {
            if (img.complete) return Promise.resolve();
            return new Promise(r => {
              const timeout = setTimeout(r, 5000);
              img.onload = () => { clearTimeout(timeout); r(); };
              img.onerror = () => { clearTimeout(timeout); img.style.display = 'none'; r(); };
            });
          })
        );

        const body = doc.body;
        body.style.width = '688px';
        body.style.padding = '0';
        body.style.margin = '0';

        const paperDims = PAPER === 'Letter'
          ? { width: 215.9, height: 279.4 }
          : { width: 210, height: 297 };
        const marginTop = 14, marginBottom = 16, marginLeft = 14, marginRight = 14;
        const contentWidthMm = paperDims.width - marginLeft - marginRight;
        const contentHeightMm = paperDims.height - marginTop - marginBottom;
        const pxPerMm = 96 / 25.4;

        const { jsPDF } = window.jspdf;
        const pdf = new jsPDF('p', 'mm', PAPER === 'Letter' ? 'letter' : 'a4');

        const blockEls = Array.from(body.children).filter(n => n.nodeType === 1);
        let cursorMm = 0;
        let pageStarted = true;

        for (const el of blockEls) {
          try {
            const canvas = await html2canvas(el, {
              scale: 2,
              useCORS: true,
              allowTaint: true,
              backgroundColor: null,
              width: 688,
              windowWidth: 688,
            });

            const imgWidthMm = contentWidthMm;
            const imgHeightMm = (canvas.height / canvas.width) * imgWidthMm;

            if (cursorMm + imgHeightMm > contentHeightMm && cursorMm > 0) {
              pdf.addPage();
              cursorMm = 0;
            }

            const imgData = canvas.toDataURL('image/png');
            pdf.addImage(imgData, 'PNG', marginLeft, marginTop + cursorMm, imgWidthMm, imgHeightMm);
            cursorMm += imgHeightMm + 2;
          } catch (blockErr) {
            console.warn('Skipping block due to render error:', blockErr);
          }
        }

        const blob = pdf.output('blob');
        generatedBlob = blob;

        // Auto-download
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = FILENAME;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        setStatus('done', 'PDF generated and downloaded successfully!');
      } catch (err) {
        console.error('PDF generation error:', err);
        setStatus('error', 'Failed to generate PDF: ' + err.message);
      }
    }

    // Start generation after page loads
    window.addEventListener('load', () => {
      setTimeout(generatePdf, 200);
    });
  </script>
</body>
</html>`;
}

function errorPage(message: string, detail?: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Quote Not Found</title>
    <style>body{font-family:system-ui;display:flex;align-items:center;justify-content:center;min-height:100vh;background:#F8FAFC;color:#334155;}
    .box{text-align:center;padding:40px;background:white;border-radius:16px;border:1px solid #E2E8F0;max-width:400px;}
    h1{font-size:20px;color:#01312D;margin-bottom:8px;}p{font-size:14px;color:#64748B;}.debug{margin-top:16px;font-size:11px;color:#94A3B8;word-break:break-all;}</style>
    </head><body><div class="box"><h1>Quote Not Found</h1><p>${escapeHtml(message)}</p>${detail ? `<p class="debug">${escapeHtml(detail)}</p>` : ""}</div></body></html>`;
}
