/*
  # PDF Studio — Templates Table

  1. New Tables
    - `pdf_templates`
      - `id` (uuid, primary key)
      - `name` (text, unique) — admin-visible template name
      - `is_active` (boolean) — only one row active at a time; active template drives PDF generation
      - `config` (jsonb) — template configuration (branding, header/footer, visibility toggles)
      - `created_at` / `updated_at` (timestamptz)

  2. Security
    - Enable RLS
    - `authenticated` users can SELECT/INSERT/UPDATE (admin area is behind admin route guard,
      service role bypass is used by Edge Functions to read the active template)
    - Anonymous (anon) SELECT allowed so the client-side pdfGenerator can load the active template

  3. Seed
    - Insert one default active template so PDF generation works immediately after migration.

  4. Notes
    - The `config` jsonb schema is tolerant — generators treat all keys as optional and fall back
      to safe defaults when fields are missing, so adding new branding fields later is safe.
*/

CREATE TABLE IF NOT EXISTS pdf_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pdf_templates_is_active_idx
  ON pdf_templates (is_active) WHERE is_active = true;

ALTER TABLE pdf_templates ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pdf_templates' AND policyname='pdf_templates read for anon'
  ) THEN
    CREATE POLICY "pdf_templates read for anon"
      ON pdf_templates FOR SELECT
      TO anon
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pdf_templates' AND policyname='pdf_templates read for authenticated'
  ) THEN
    CREATE POLICY "pdf_templates read for authenticated"
      ON pdf_templates FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pdf_templates' AND policyname='pdf_templates insert for authenticated'
  ) THEN
    CREATE POLICY "pdf_templates insert for authenticated"
      ON pdf_templates FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pdf_templates' AND policyname='pdf_templates update for authenticated'
  ) THEN
    CREATE POLICY "pdf_templates update for authenticated"
      ON pdf_templates FOR UPDATE
      TO authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

INSERT INTO pdf_templates (name, is_active, config)
SELECT 'Default', true, jsonb_build_object(
  'brand', jsonb_build_object(
    'primaryColor', '#01312D',
    'accentColor', '#BFF102',
    'accentDark', '#307C31',
    'textColor', '#01312D',
    'mutedColor', '#64748B',
    'backgroundColor', '#FFFFFF',
    'logoUrl', '',
    'fontFamily', 'Helvetica, Arial, sans-serif'
  ),
  'header', jsonb_build_object(
    'title', 'Custom Shade Sail Quote',
    'tagline', 'Where Cool Spaces Begin'
  ),
  'footer', jsonb_build_object(
    'line1', 'Generated by ShadeSpace Professional Configurator',
    'line2', 'Visit shadespace.com for more information'
  ),
  'sections', jsonb_build_object(
    'showSummary', true,
    'showMeasurements', true,
    'showAnchorPoints', true,
    'showHardwareBreakdown', true,
    'showPriceBreakdown', true,
    'showGuarantee', true,
    'showPricingCallout', true
  ),
  'paper', 'A4'
)
WHERE NOT EXISTS (SELECT 1 FROM pdf_templates WHERE name = 'Default');
